### PR TITLE
[enterprise-3.11] Bug 1652645 - Webhook urls in configuration page are invalid with undefined included

### PR DESCRIPTION
**Pull request by jhadvig**
Port of https://github.com/openshift/origin-web-console/pull/3097

@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
Needs https://github.com/openshift/release/pull/2262 to enable Jenkins

**Comment by spadgett** [comment]
Closing and reopening to try and kick Jenkins.

**Comment by jhadvig** [comment]
The tests are still being skipped :-/

**Comment by jhadvig** [comment]
@spadgett PTAL

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
