### PR TITLE
Add SVG icons

### PR DESCRIPTION
**Pull request by spadgett**
Icons from @jennyhaines

Requires https://github.com/openshift/origin-web-catalog/pull/465
Requires https://github.com/openshift/origin-web-common/pull/213

screen shot 2017-10-03 at 3 03 29 pm

Before and After:

screen shot 2017-10-04 at 9 42 10 am

@serenamarie125 @sspeiche @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
Icons for subcategories:

openshift web console 2017-10-04 09-43-19

**Comment by sspeiche** [comment]
Ooohhhh purdy

**Comment by spadgett** [comment]
@jeff-phillips-18 PTAL

**Comment by benjaminapetersen** [comment]
[test] since [Jenkins file changed](https://github.com/openshift/aos-cd-jobs/pull/709)

**Comment by benjaminapetersen** [comment]
dist on this one, not tests

**Comment by spadgett** [comment]
> dist on this one, not tests

Yeah, needs a common and catalog release before I can add dist

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
