### PR TITLE
Switching column layout to Bootstrap grid

### PR DESCRIPTION
**Pull request by rhamilto**
and other misc. cleanup.  Fixes [BZ-1350710](https://bugzilla.redhat.com/show_bug.cgi?id=1350710).

@sg00dwin, PTAL.

### CODE REVIEW

**Comment by sg00dwin** [comment]
@rhamilto looks good to me and it checked out on browserstack.

**Comment by rhamilto** [comment]
@jwforres or @spadgett, PTAL.

**Comment by benjaminapetersen** [comment]
Nice looks clean.

**Comment by jwforres** [comment]
LGTM.  I doubt its an issue, but did you double check what happens when you use the text filter box? Just asking because whole categories can disappear when using the filter.

**Comment by rhamilto** [comment]
> LGTM. I doubt its an issue, but did you double check what happens when you use the text filter box? Just asking because whole categories can disappear when using the filter.

Good question!  I just double checked, and it looks ok.

screen shot 2016-07-05 at 4 34 02 pm


screen shot 2016-07-05 at 4 33 05 pm

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
