### PR TITLE
[WIP] Membership page w/pf-list

### PR DESCRIPTION
**Pull request by benjaminapetersen**
RE issue #1219, based on wireframes provided by @sg00dwin 
Quick hack on membership, prototyping a pf-list style that looks like the overview, monitoring, etc.

screen shot 2017-07-18 at 4 24 12 pm

@jwforres @spadgett

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Curious if anyone had further thoughts on this as a solution to some of the quirky layout problems on the membership page.  Lots more screenshots from @sg00dwin on #1219. 

@sg00dwin @spadgett @rhamilto ?

**Comment by rhamilto** [comment]
Can you add a screenshot with a row expanded?  Without it, it's hard for me to understand why they collapse exists...

**Comment by benjaminapetersen** [comment]
@rhamilto look @sg00dwin issue #1219 as he has a ton of screenshots illustrating what this could look like if the work was completed.

**Comment by benjaminapetersen** [comment]
Closing this out, I'm sure will be obsolete after @sg00dwin's updates & is only a prototype.  We can revisit this concept in the future.

**Pull request closed without merging**
