### PR TITLE
Show services with alternates as top-level services on overview

### LINKED ISSUE #631: Service can be hidden on overview if it's an alternate service to another dependent service
In some edge cases, a service can be hidden:

* Service A depends on service B
* Route B has primary service B and alternate service C
* Service C will not be displayed on the overview

/cc @jwforres @jorgemoralespou

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #631
@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett what does this look like then if you have grouped either the primary or one of the alternates to another service

**Comment by spadgett** [comment]
It shows up twice, which is not ideal. We already do this for services that have dependents, but are dependents themselves. I was planning on opening an issue about it because there are many cases where we show the same deployment twice on the overview, for instance, if it has more than one service.

Here is a screenshot:

screen shot 2016-10-06 at 11 06 10 am

**Comment by jwforres** [comment]
Ok i think this is a reasonable change to backport to 3.3.1 since it at least gets rid of the loss of the service

I think we need to just have a larger discussion about linking in combination with A/B

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
