### PR TITLE
Include vendor prefixes required for consistent styling of placeholder text

### PR DESCRIPTION
**Pull request by sg00dwin**
Was removed from patternfly

fixes https://github.com/openshift/origin-web-console/issues/1259

### CODE REVIEW

**Comment by spadgett** [comment]
We should create a follow on issue to remove these styles when it's fixed upstream in Patternfly

**Comment by sg00dwin** [comment]
@spadgett follow on issue created

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
This pr is now rebased

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
@sg00dwin 

```
$ hack/clean-deps.sh && hack/install-deps.sh && grunt build
```

**Comment by sg00dwin** [comment]
@spadgett I ran those. Is it still showing a diff?

**Comment by spadgett** [comment]
@sg00dwin Yeah, it's seeing a diff in vendor.js, which shouldn't be in the commit

**Comment by sg00dwin** [comment]
updated vendor.js added

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
