### PR TITLE
Remove hover opacity change from the metrics-donut to be consistent with the pods-donut

### PR DESCRIPTION
**Pull request by sg00dwin**
@spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
We have other donuts if you want to remove the opacity from them all. But I like the effect. I'm not sure we should remove it everywhere. We had a specific reason to on the overview.

To be honest, I'd almost rather revert the change to the overview donuts.

cc @jwforres @ajacobs21e

**Comment by sg00dwin** [comment]
The opacity change from donut charts on the overview addressed usability issue openshift/origin#9253 I assumed we would be consistent is how these behave.

**Comment by spadgett** [comment]
Right, I understand why we made the change. I feel like we made the general usability worse to fix an edge case, though. The opacity change is another helpful cue that the tooltip is only for that arc you're hovering over.

**Comment by ajacobs21e** [comment]
I think it's difficult since we use so many close shades of blue. Is it an option to change some of the colors?
Is it possible to fade the non-highlighted portions more (aka make them very light) so that it doesn't conflict with our status colors?

**Comment by spadgett** [comment]
> I think it's difficult since we use so many close shades of blue. Is it an option to change some of the colors?

This was deliberate in that the pod transitions from running, not ready (light blue) to running and ready (blue). We wanted to use blue consistently to indicate running. The states are similar. (If the pod takes too long to get ready, we change the color to orange as a warning.)

> Is it possible to fade the non-highlighted portions more (aka make them very light) so that it doesn't conflict with our status colors?

This might be possible. @sg00dwin Do we have control over the opacity?

**Comment by sg00dwin** [comment]
@spadgett @ajacobs21e yes we can override the default opacity change for the defocused state, which is `.c3-defocused {opacity: .3} ` 

**Here are some example for an opacity of .2**
defocused2-pulling
defocused2-running
defocused2-terminating

**And here is .15**
at this point the light gray pretty much falls out
defocused1 5-pulling
defocused1 5-running
defocused1 5-terminating
defocused1 5-pending

**Comment by spadgett** [comment]
Replaced by #1079

**Pull request closed without merging**
