### PR TITLE
Update ::selection styles for log text & link highlighting to be consistent across browsers

### PR DESCRIPTION
**Pull request by sg00dwin**
…
Fixes https://github.com/openshift/origin-web-console/issues/2724

screen shot 2018-01-30 at 4 42 44 pm
screen shot 2018-01-30 at 4 37 18 pm
screen shot 2018-01-30 at 4 40 43 pm
screen shot 2018-01-30 at 4 48 19 pm

### CODE REVIEW

**Comment by rhamilto** [comment]
It looks like need to rebase, install deps, and rebuild.

**Comment by sg00dwin** [comment]
@rhamilto updated

**Pull request merged**
