### PR TITLE
Add an events sidebar directive

### PR DESCRIPTION
**Pull request by spadgett**
Add an events sidebar to be used in the monitoring page. This PR only adds the directive. It's not yet visible on any page.

banners_and_alerts_and_openshift_web_console

@jwforres PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
Changing the info icon to text-muted:

banners_and_alerts_and_openshift_web_console

**Comment by jwforres** [comment]
LGTM, if we need to we can tweak it in the monitoring page pr  [merge]

**Comment by jwforres** [comment]
@spadgett looks like it failed on the dist

**Comment by spadgett** [comment]
Ran clean deps, install deps and seeing a new Bootstrap version.

**Comment by jwforres** [comment]
Looks like Travis passed so should be good now

**Pull request merged**
