### PR TITLE
Fix references to Logger that are using the wrong one

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin-web-console/issues/818

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
Wonder if there's a way to guard against this in the future. Is the other Logger coming from Hawtio?

**Comment by jwforres** [comment]
@spadgett it is, we could call ours something different

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
I think we should remove the `Logger` global from jshintrc:

https://github.com/spadgett/origin-web-console/blob/22cbe94128168282f06b4e52766f05170a77df92/.jshintrc#L30

**Pull request merged**
