### PR TITLE
Partial backport of 0db39ea - Make sure latest data is always sent to…

### PR DESCRIPTION
**Pull request by jwforres**
… callback when using cached data

Fixes https://github.com/openshift/origin-web-console/issues/517

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett realized I never opened this partial backport like we had discussed, see #517

**Comment by jwforres** [comment]
dont merge it yet, just needs review

**Comment by spadgett** [comment]
LGTM, although travis sees a dist mismatch

**Comment by jwforres** [comment]
could be something in the npm build chain, i'll do a full clean / install on that branch

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
