### PR TITLE
Update pipeline styles, allow stages to wrap

### LINKED ISSUE #74: Improve pipeline stage content wrapping on browse page
The icons aren't vertically aligned when one of the stage names is long.

openshift_web_console

/cc @sg00dwin

### PR DESCRIPTION
**Pull request by spadgett**
@jwforres Thoughts on this change?

Updated styles:

openshift_web_console

Wrapping stages:

openshift_web_console

Fixes #74

### CODE REVIEW

**Comment by jwforres** [comment]
i feel like the wrapped stages need separators

**Comment by spadgett** [comment]
If we have the separators, will they look too much like different pipelines?

**Comment by spadgett** [comment]
@sg00dwin and I also talked about having a scrollbar instead of wrapping. I can't decide. I worry that you might not be able to see a running / failed stage if off-screen.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
