### PR TITLE
Bug 1449949 - Group pods by owner reference

### PR DESCRIPTION
**Pull request by spadgett**
This cannot be merged until adding owner refs to old pods is complete (https://github.com/openshift/origin/issues/14174).

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1449949

### CODE REVIEW

**Comment by spadgett** [comment]
cc @jwforres

**Comment by spadgett** [comment]
@mfojtik FYI, this changes the web console to use owner refs for the following associations:

pods -> replica set
pods -> replication controller
pods -> stateful set
replica sets -> deployment

**Comment by spadgett** [comment]
Blocked by https://github.com/openshift/origin/issues/14174

**Comment by spadgett** [comment]
@jwforres Thinking about splitting this into two PRs, one for replica sets -> deployments and one for pod owner references. Then we can fix https://bugzilla.redhat.com/show_bug.cgi?id=1449908 without needing https://github.com/openshift/origin/issues/14174

**Comment by jwforres** [comment]
works for me

**Comment by spadgett** [comment]
Opened #1553 with just the replica set -> deployment change

**Comment by spadgett** [comment]
Since #1553 merged, rebased and updated the PR to be specifically for pod owner references.

**Comment by jwforres** [comment]
LGTM other than needing dist and needing to wait for the origin PR

**Comment by spadgett** [comment]
No longer blocked by https://github.com/openshift/origin/issues/14174

@jwforres added dist

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
