### PR TITLE
Attach storage form updates

### PR DESCRIPTION
**Pull request by spadgett**
* Align breadcrumbs with content
* Clean up margins around help text
* Change "create storage" to "request storage" for consistency with the action name on other pages

Before:

screen shot 2016-11-02 at 8 02 17 am

After (updated text called out):

screen shot 2016-11-02 at 8 12 45 am

@jwforres PTAL. The large diff is mostly from whitespace changes.

@erinboyd @zherman0 CC

### CODE REVIEW

**Comment by jwforres** [comment]
So the change on this page to "create storage" was intentional based on
feedback during the design review.  Sounds like we need to change "Request
Storage" to "Create Storage" in some more places

**Comment by spadgett** [comment]
Update to use "create storage" everywhere.

screen shot 2016-11-02 at 10 06 36 am

**Comment by spadgett** [comment]
Minor updates to the wording:

screen shot 2016-11-02 at 10 17 24 am

**Comment by jwforres** [comment]
changes LGTM

[merge]

**Pull request merged**
