### PR TITLE
Updating PatternFly and Angular-PatternFly to v3.3.5

### PR DESCRIPTION
**Pull request by rhamilto**
@jwforres, @spadgett:  this looks good to me, but it probably makes sense for you all to pull the changes and test since I'm not as well versed in all areas of the console.

### CODE REVIEW

**Comment by jwforres** [comment]
@benjaminapetersen is this going to conflict with your bower bump PR, were you already updating patternfly there?

@rhamilto does this actually pull in the visual change to the code block that got merged yesterday

**Comment by rhamilto** [comment]
> @rhamilto does this actually pull in the visual change to the code block that got merged yesterday

Are you meaning https://github.com/patternfly/patternfly/pull/284?  If so, no it won't be as that will require a new PatternFly release.

**Comment by jwforres** [comment]
@rhamilto ok hold off cause thats what i wanted to pick up :)

**Comment by rhamilto** [comment]
@jwforres We could pick up the commit without waiting for a release by specifying a commit hash (e.g., 603a5dc19887e731f8b7a5d6a6032ddc9cbba061) instead of a version in [bower.json](https://github.com/rhamilto/origin-web-console/blob/0aca15e98d647dcb2a64060df3837cf764f1e8ba/bower.json#L19).

I did so in my dev environment.  The only resulting changes over v3.3.5 is the exact change you're looking for. 

Here's a few examples of the result.

screen shot 2016-05-16 at 5 52 34 pm
screen shot 2016-05-16 at 5 55 04 pm
screen shot 2016-05-16 at 5 56 13 pm

In context, I'm starting to wonder if this change makes &lt;code&gt; look too much like a link?

cc: @sg00dwin, @benjaminapetersen

**Comment by spadgett** [comment]
> In context, I'm starting to wonder if this change makes code look too much like a link?

Yeah, I'm starting to think it does, too. I noticed the OpenShift docs use this style for block elements, but not inline. For instance,

https://docs.openshift.org/latest/admin_guide/manage_users.html#managing-users-deleting-a-user

"oc get user" inline is red, but the full examples are blue.

**Comment by spadgett** [comment]
Wondering how gray background with black or a darker blue looks. Maybe #004368 ?

**Comment by benjaminapetersen** [comment]
Hmm. Yeah, agree as well.

**Comment by rhamilto** [comment]
> Wondering how gray background with black or a darker blue looks. Maybe #004368 ?

screen shot 2016-05-17 at 10 05 01 am

**Comment by sg00dwin** [comment]
more options...

screen shot 2016-05-17 at 10 16 00 am

screen shot 2016-05-17 at 10 12 15 am

**Comment by benjaminapetersen** [comment]
@jwforres sorry missed that, nope, Patternfly was one of the dependencies I left alone since @rhamilto has been working on it.

**Comment by rhamilto** [comment]
The PatternFly team has a pending PR to change the colors.  See https://github.com/patternfly/patternfly/pull/289#issuecomment-219809692

**Comment by rhamilto** [comment]
Closing as PatternFly and Angular-PatternFly v3.4.0 are now out, and I'll open a new PR with that version.

**Pull request closed without merging**
