### PR TITLE
Updated processTemplate to call ProjectServices.create(...)

### LINKED ISSUE #1895: Landing page projects sidebar should show most recently accessed
Currently the landing page projects sidebar shows the 5 most recently created. It'd be better to show the 5 most recently accessed. We could implement this using `localStorage` like we have done for recently-viewed services.

cc @openshift/team-ux-review @jeff-phillips-18 @dtaylor113 @rhamilto

### PR DESCRIPTION
**Pull request by dtaylor113**
This is the final PR which fixes #1895.

I cannot get templates to load in my dev system, so leaving [WIP] until able to verify that when adding a template service and creating a new project at the same time -the new project is created and is listed first in the project summary sidebar.

During coding I was able to see templates, and this code worked, but now I cannot get templates, so I can't test this final PR.  @jeff-phillips-18, if you have a few free cycles, could you please clone this PR and verify this usecase?  -thanks!

### CODE REVIEW

**Comment by spadgett** [comment]
Hey @dtaylor113 can you make sure `template_service_broker ` is false? It needs to be false to see the `process-template` dialog.

https://github.com/spadgett/origin-web-console/blob/93d43b0ba4dce2ac5b367f9673039bb3bf3ccaae/app/scripts/constants.js#L92

**Comment by spadgett** [comment]
Your changes are working correctly for me.

**Comment by spadgett** [comment]
[test]

**Comment by dtaylor113** [comment]
> Hey @dtaylor113 can you make sure template_service_broker is false? It needs to be false to see the process-template dialog.

Well, that would've saved me a day of installing packages :-)   Yes, setting` template_service_broker`to false got me all 31 items!   I was setting all flags in ENABLE_TECH to true.  What does `pod_presets` do?

**Comment by dtaylor113** [comment]
Also, @spadgett, @jeff-phillips-18 and I were wondering why the templates seem to be copies of the service classes?  And, does it matter that end-users can't tell the difference between service-classes, builder images, or templates when adding them from the catalog?

**Comment by spadgett** [comment]
@dtaylor113 The idea is you use the templates only if you've disabled the template broker. In that case, there wouldn't be template service classes, so you wouldn't see duplicates.

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
`pod_presets` changes how we do bindings. If true, we will inject the config for a service as env vars into your pod.

**Pull request merged**
