### PR TITLE
Use angular-moment for relative timestamps

### PR DESCRIPTION
**Pull request by spadgett**
https://github.com/urish/angular-moment

Fixes https://github.com/openshift/origin/issues/7591

@benjaminapetersen @jwforres

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Nice... 47 file changes, oi.

**Comment by jwforres** [comment]
guessing travis failed because of an issue with the bower update, we'll see

[merge]

@juanvallejo this change may conflict with your services PR, will probably need to update your directives you created to switch from using `<relative-timestamp>`

**Comment by spadgett** [comment]
Updated karma.conf with dependency

[merge]

**Comment by spadgett** [comment]
@benjaminapetersen 48 files now (hooray for macros)

**Pull request merged**
