### PR TITLE
Updates to control margin of annotations block

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://github.com/openshift/origin-web-console/issues/1083
screen shot 2017-01-09 at 2 30 33 pm
screen shot 2017-01-09 at 2 42 06 pm
screen shot 2017-01-09 at 2 43 46 pm
screen shot 2017-01-09 at 2 43 36 pm

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett PTAL
I'm now setting the appropriate margin on the annotations content.

**Comment by spadgett** [comment]
@sg00dwin I'd argue the problem is that the `table:last-child` rules are being applied to tables when they shouldn't be. We should only have 0 margin for a table when it's the last thing on the page. If we have to special case margins anyway, then I'd almost rather remove the `:last-child` rules.

cc @rhamilto

**Comment by sg00dwin** [comment]
@spadgett the bottom margin of the table needs to be 0 so that extra space isn't added to the the global bottom spacing set on the `container-fluid`. Are you suggesting, instead of removing it with [this rule](https://github.com/sg00dwin/origin-web-console/blob/4f87fadd75e94b9e4e621cf4ef3a8c56abd7b3fe/app/styles/_substructure.less#L295) do you want `class="mar-none"` add to these tables.

**Comment by spadgett** [comment]
@sg00dwin I'm suggesting we try to fix the rule so it only applies when the table is the last thing on the page, if possible. If not, we should discuss alternatives. I don't think we should keep a rule that applies to any table that is the last child of any element. It will cause more problems than it helps.

**Comment by sg00dwin** [comment]
@spadgett To my knowledge their is no way, using just css, to target only the last table on any page, since their nested markup structures vary from page to page. @rhamilto let me know if I'm wrong.

On almost all pages that have table(s) within `.middle-content` the table is the last item on the page, which is the reason I used `.middle-content .table:last-child` to remove it's bottom margin and then selectively add margin on the few cases where bottom margin is needed. specifically the `pods-table` & `traffic-table` 

This seemed more preferable than going through each page and manually adding `.mar-bottom-none` to the last table. But then there could be cases where we don't know what the last table will be.

Which way would you prefer?

**Comment by spadgett** [comment]
My opinion: I'd rather remove the `table:last-child` rule, remove the bottom margin from `.middle-content`, and use the normal bottom margin of the last element on the page. If the last element doesn't have a bottom margin, we'd just add one.

I think a rule that sometimes applies to tables and sometimes doesn't is going to lead to other unexpected bugs like #1083 as we change the markup. Wrapping a table in a `<div class="table-responsive">` or an `<div ng-if="...">` element seems really common and will unexpectedly change the margin. Stuff like that is really hard to catch on code reviews.

Open to suggestions, though. @rhamilto thoughts?

**Comment by rhamilto** [comment]
> I think a rule that sometimes applies to tables and sometimes doesn't is going to lead to other unexpected bugs like #1083 as we change the markup.

Agreed since our templates seem to vary so much from page to page.  When I initially proposed this rule, I assumed we could make it specific enough to avoid these issues by using a [child selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_selectors), but that didn't work in practice because of the markup inconsistency.  :(

**Comment by sg00dwin** [comment]
Ok, so I will put together a pr remove the [global bottom margin](https://github.com/openshift/origin-web-console/blob/master/app/styles/_substructure.less#L89) and [these rules](https://github.com/openshift/origin-web-console/blob/master/app/styles/_substructure.less#L284-L317) that zeroed out the bottom margin on various elements positioned at the end of pages. 

Then go through each page and ensure there is a bottom margin on all pages and add one if needed. Noting that the margin could vary based on the type of ui element that is positioned last.

**Pull request closed without merging**
