### PR TITLE
Remove layout.attr flex attribute 

### PR DESCRIPTION
**Pull request by sg00dwin**
which was recently updated[[1](https://github.com/openshift/origin-web-console/commit/782b8bcf6d46eff3eefc23cc7412caa2e3950663#diff-165cbcede4a6481e21bc7dd1fbaee5d5R134)] and introduced this bug

Fixes https://github.com/openshift/origin-web-console/issues/837

screen shot 2016-11-07 at 2 15 22 pm

### CODE REVIEW

**Comment by sg00dwin** [comment]
cc @spadgett @rhamilto

**Comment by spadgett** [comment]
@sg00dwin It worries me a bit we might have this problem in other places now. Should we rollback the other change?

https://github.com/openshift/origin-web-console/commit/782b8bcf6d46eff3eefc23cc7412caa2e3950663#diff-165cbcede4a6481e21bc7dd1fbaee5d5R134

**Comment by spadgett** [comment]
Any chance that change caused #833?

**Comment by sg00dwin** [comment]
@spadgett yes it is causing #833 as well as collapsing the 'add' button in the header at mobile[2]. @benjaminapetersen I think we should remove [line 134](https://github.com/openshift/origin-web-console/commit/782b8bcf6d46eff3eefc23cc7412caa2e3950663#diff-165cbcede4a6481e21bc7dd1fbaee5d5R134) and look at addressing the IE collapse issue separately.

[2] 
flex-basis-issue

**Comment by benjaminapetersen** [comment]
@sg00dwin @spadgett I suggested moving lines 134... up into the `.membership { }` block, that would eliminate any bugs like this.

**Comment by benjaminapetersen** [comment]
I can PR that if you think it is reasonable? it would isolate to my membership page only then.

**Comment by sg00dwin** [comment]
closing this and [new opening pr](https://github.com/openshift/origin-web-console/pull/851) to move offending rule

**Pull request closed without merging**
