### PR TITLE
Update CreateFromUrl controller to use getPreferredVersion

### PR DESCRIPTION
**Pull request by benjaminapetersen**
no `canI` in view

@spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
@benjaminapetersen Suggest we defer this one since we don't test these often in day-to-day development. I know we have automated tests, but I'd rather leave it for 3.8 just in case.

**Comment by benjaminapetersen** [comment]
@spadgett works for me.

**Comment by benjaminapetersen** [comment]
Updated.
Watching the build on this one as we have a good # of tests covering.

**Pull request merged**
