### PR TITLE
Add product icons for service catalog

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/aRRQ5F57

screen shot 2017-10-19 at 12 19 29 pm

@jwforres @sspeiche

### CODE REVIEW

**Comment by spadgett** [comment]
screen shot 2017-10-19 at 12 08 20 pm

**Comment by spadgett** [comment]
cc @serenamarie125 @jennyhaines

**Comment by spadgett** [comment]
Some duplicate items in my screenshot. Let me fix that.

**Comment by jennyhaines** [comment]
Nice! Looks so much better with those icons, @spadgett ! It'll be even more awesome once those icons in the recently view section are sized up to 30px.

**Comment by sspeiche** [comment]
Don't forget to notice that the display names have been updated too to be more concise.

Looks nice @spadgett Thanks all!

**Comment by spadgett** [comment]
@sspeiche It looks so much better with your updates

**Comment by jennyhaines** [comment]
@spadgett - Just got word from branding that they are doing the very last tweaks to the icons...and have one more on the way. I will get those updated ones tomorrow around noon. Could those make it in before this code freeze? Also, did you try putting the new icons into the ordering panel? It would be nice to see it in there as well. @serenamarie125

**Comment by spadgett** [comment]
> Could those make it in before this code freeze? 

Yeah, we'll make sure they get in.

> Also, did you try putting the new icons into the ordering panel? It would be nice to see it in there as well.

screen shot 2017-10-19 at 2 03 56 pm

**Comment by jennyhaines** [comment]
@spadgett That looks nice at a larger size! Thanks.

**Comment by jennyhaines** [comment]
Hi Sam - The one icon I'm a little unsure about is the JBoss A-MQ one with the message bubbles. Do you think you could size up the "Recently Viewed" icons to 30px so I can see if the details are still visible on the icon? (Trying to figure out whether we need to up the contrast for low res monitors.)

**Comment by spadgett** [comment]
The recently viewed icons were previously 27px by 27px. Here is 30px by 30px on a non-retina display:

openshift web console 2017-10-19 14-35-11

**Comment by jennyhaines** [comment]
Thank you @spadgett - this is super helpful!

**Comment by jennyhaines** [comment]
One more size tweak and I'll get out of your hair for now @spadgett . (I know this is the definition of nit-picky.) Those icons could really go up to 32px. I think that would be the best size. I just tested with square icons). Thanks!

**Comment by spadgett** [comment]
32px:

openshift web console 2017-10-19 15-11-16

**Comment by serenamarie125** [comment]
I really like them in the catalog and in the ordering flow!  agree that as recently viewed services, they may not look the best though.

@spadgett what about the search dropdown?

**Comment by jennyhaines** [comment]
bitmoji

**Comment by spadgett** [comment]
openshift web console 2017-10-19 15-12-36

**Comment by spadgett** [comment]
Ignore the duplicates :) That is from a local config setting

**Comment by serenamarie125** [comment]
Looks great @spadgett !!!

**Comment by spadgett** [comment]
The 32px size change needs to happen in the origin-web-catalog repo. @sg00dwin can you look at that as a fix for https://github.com/openshift/origin-web-catalog/issues/506 ?

**Comment by jennyhaines** [comment]
@spadgett - I'm curious how the 3scale icon looks in the search dropdown? That icon is very detailed.

**Comment by spadgett** [comment]
> I'm curious how the 3scale icon looks in the search dropdown? That icon is very detailed.

I don't think we have anything in the catalog currently using, but I created a dummy service with the icon:

openshift web console 2017-10-19 15-35-23

openshift web console 2017-10-19 15-36-08

openshift web console 2017-10-19 15-36-23

32px:

openshift web console 2017-10-19 15-37-15

**Comment by serenamarie125** [comment]
@spadgett thanks for getting these in so quickly!

**Comment by spadgett** [comment]
> I will get those updated ones tomorrow around noon.

@jennyhaines Any update on the icons? The cutoff for features is today. We could add what we have an update them as a bug fix later if needed.

**Comment by jennyhaines** [comment]
Yes @spadgett ! Just gut the updated ones! [https://drive.google.com/drive/folders/0Byx88a2G0Sw4SGpXLTk0bmZyMDA?usp=sharing](https://drive.google.com/drive/folders/0Byx88a2G0Sw4SGpXLTk0bmZyMDA?usp=sharing)

**Comment by spadgett** [comment]
/hold

Need to update to latest icons.

**Comment by spadgett** [comment]
Thanks @jennyhaines !

**Comment by spadgett** [comment]
/hold cancel

Updated with the latest. @jwforres PTAL

**Comment by spadgett** [comment]
screen shot 2017-10-20 at 3 46 58 pm

**Pull request merged**
