### PR TITLE
Updating kubernetes label filter overall structure to use flexbox css and various refinements

### PR DESCRIPTION
**Pull request by sg00dwin**
- Fix for https://github.com/openshift/origin/issues/8156 where filter would overlap view toggle controls
	- move dropdown menu data-placement to body to address edge case where long values could be clipped outside of scrollable area
	- wrapping of labels allows for better utilization of space within data-toolbar 
     - Add on focus state

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres flexified label selector pr ftw
cc @spadgett 

**before and after screenshots of various fixes**

overlap
--
clipped
--
tighter-flow
--
builds
--
iphone6-landscape
--
iphone320

**Comment by jwforres** [comment]
LGTM, did you double check the filter where its directly adjacent to a table like on the build config or deployment config pages?

**Comment by benjaminapetersen** [comment]
Nice, looks much better.

**Comment by sg00dwin** [comment]
[test]

**Comment by jwforres** [comment]
[merge]

**Comment by sg00dwin** [comment]
Fixes https://github.com/openshift/origin/issues/8156

**Pull request merged**
