### PR TITLE
Correct binding name

### LINKED ISSUE #2183: Look at consistency around the names of provisioned services and bindings
We should look into being consistent around the names we use for provisioned services--sometimes we use the Service Class Display Name (e.g. in the catalog and the project overview), and in other cases we use the service instance name. Similarly, with bindings we have the binding resource and the secret.

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #2183
Requires https://github.com/openshift/origin-web-common/pull/241

screen shot 2017-10-31 at 11 45 50 am
screen shot 2017-10-31 at 12 12 59 pm
screen shot 2017-10-31 at 1 18 12 pm

### CODE REVIEW

**Comment by spadgett** [comment]
LGTM pending common release.

**Comment by rhamilto** [comment]
Ready for final review, @spadgett.

**Pull request merged**
