### PR TITLE
Use correct HTTP status from failed DataService.list

### LINKED ISSUE #2354: Deploy image dialog should not show an error when it can't list secrets
Currently, you see an error toast when the deploy image dialog can't list secrets. It should suppress this error since they're not needed and only there as options for the env value from options.

### PR DESCRIPTION
**Pull request by spadgett**
Bumps origin-web-common to 0.0.69

Requires https://github.com/openshift/origin-web-common/pull/236
Fixes #2354

### CODE REVIEW

**Comment by jwforres** [comment]
so all the list error handlers were broken?

are there list calls in catalog that we would need to fix?

**Comment by spadgett** [comment]
> so all the list error handlers were broken?

Yeah :/

> are there list calls in catalog that we would need to fix?

I swept all 3 repos looking at list calls. The ones in the catalog repo weren't doing anything with the failure args (catalog service)

**Comment by jwforres** [comment]
lgtm, just needs the common update it depends on

**Comment by spadgett** [comment]
Updated with dist

@jwforres The logos changes in the dist are because we cut a logos release and we were using a `^` in bower.json. @rhamilto is removing the `^` in #2367

**Comment by spadgett** [comment]
Rebased

@jwforres another look?

**Pull request merged**
