### PR TITLE
Fixes visual defects around "Container:" labels

### LINKED ISSUE #1180: No space between label and container name on logs tab
openshift_web_console

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1180

screen shot 2017-06-21 at 4 39 03 pm

Bonus:

* improves display of dash following container name
* fixes alignment of container name on metrics tab

screen shot 2017-06-21 at 4 40 07 pm

### CODE REVIEW

**Comment by spadgett** [comment]
Looks like we need to make the same vertical align change to the container name dropdown when there's more than one container:

openshift web console 2017-06-22 09-39-46

**Comment by spadgett** [comment]
@rhamilto you can use this YAML

https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json

**Comment by rhamilto** [comment]
Good catch, @spadgett.  Fixed.
screen shot 2017-06-22 at 10 45 31 am

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
