### PR TITLE
Updates to membership page to prevent breaking. This is a back port of an initial fix that went in 3.7.

### PR DESCRIPTION
**Pull request by sg00dwin**
Original pr https://github.com/openshift/origin-web-console/pull/2344

Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1545089

localhost_9000_dev-console_oauth 9
localhost_9000_dev-console_oauth 8
localhost_9000_dev-console_oauth 7
localhost_9000_dev-console_oauth 6
localhost_9000_dev-console_oauth 5
localhost_9000_dev-console_oauth 4
localhost_9000_dev-console_oauth 3
localhost_9000_dev-console_oauth 2
localhost_9000_dev-console_oauth 1
localhost_9000_dev-console_oauth

### CODE REVIEW

**Comment by sg00dwin** [comment]
cc @rhamilto @benjaminapetersen

**Comment by spadgett** [comment]
Looks like flake #2105

/retest

**Comment by benjaminapetersen** [comment]
server failed to start 

/retest

**Pull request merged**
