### PR TITLE
[enterprise-3.11] Bump PatternFly to v3.59.0 to pick up Bootstrap fixes

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1656438

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
@spadgett we're good to go :)

**Comment by spadgett** [comment]
We'll need https://github.com/openshift/aos-cd-jobs/pull/1680 to fix CI

**Comment by jhadvig** [comment]
@spadgett we need to merge this one in order to get rid of the failure, for which other 3.11 PRs are failing.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
