### PR TITLE
Update attachPVC controller to use new DataService.list

### PR DESCRIPTION
**Pull request by benjaminapetersen**
re: #799

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett minor tweak to plug away @ that list.

**Comment by jwforres** [comment]
@benjaminapetersen looks like you have an unrelated dist change in main.css

**Comment by benjaminapetersen** [comment]
Oop, thx, removed it.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
