### PR TITLE
Added bread crumb for routes main page when on the create routes page

### PR DESCRIPTION
**Pull request by zherman0**
There was no bread crumb back to the main routes page from the create new routes form
@jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
Will need to run grunt build and include the updated dist/* files 

Cc @spadgett since you built this page, any concern?

**Comment by spadgett** [comment]
No concerns. Looks good to me

**Comment by spadgett** [comment]
@zherman0 ping, do you mind running grunt build and adding dist/ to the commit?

**Comment by zherman0** [comment]
Yes, I will add them.


On Mon, Jul 11, 2016 at 5:43 PM, Sam Padgett <notifications@github.com>
wrote:

> @zherman0 <https://github.com/zherman0> ping, do you mind running grunt
> build and adding dist/ to the commit?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openshift/origin-web-console/pull/137#issuecomment-231898128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AR3HmcsvdUT8Ib3_4kudyou4m4SQdJyyks5qUtULgaJpZM4JGnLg>
> .
>



-- 
Zac Herman
<zherman@redhat.com>
Emerging Tech - Senior Software Engineer
Red Hat Inc

**Comment by spadgett** [comment]
Thanks!

[merge]

**Pull request merged**
