### PR TITLE
fix kibana archive link for operations

### PR DESCRIPTION
**Pull request by jcantrill**
This is a backport of #3060 for release-3.10 to fix https://bugzilla.redhat.com/show_bug.cgi?id=1624406

### CODE REVIEW

**Comment by jcantrill** [comment]
@spadgett 
`grunt test` fails for me with:

```
Running "connect:test" (connect) task
Started connect web server on https://localhost:9000

Running "karma:unit" (karma) task
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: [$injector:nomod] Module 'openshiftConsole' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
  http://errors.angularjs.org/1.5.11/$injector/nomod?p0=openshiftConsole
  at bower_components/angular/angular.js:2135

```
Only change might be https://github.com/openshift/origin-web-console/pull/3086/files#diff-2177e2691ee1e73403114c08f4d7eda6R3 since building and testing without this PR results in success

**Comment by spadgett** [comment]
I have a suspicion that your service script is being loaded by karma before app.js. We might need to look at the order files are included in karma.conf.js.

Note also CI is currently broken on this branch :(

**Comment by jcantrill** [comment]
@spadgett found it. new file was not under 'app/script/services' but thats where we included it

**Comment by jcantrill** [comment]
@spadgett I have manually and tested and confirmed this PR:
* properly routes admins to both operations and application logs
* properly routes non-admins to application logs

**Pull request closed without merging**
