### PR TITLE
Update origin-web-common to 0.0.31, origin-web-catalog to 0.0.19

### PR DESCRIPTION
**Pull request by jeff-phillips-18**

### CODE REVIEW

**Comment by spadgett** [comment]
Do we need the changes from #1625 when we bump origin-web-common?

cc @rhamilto

**Comment by spadgett** [comment]
I think we can remove `applicationHasDeployment` and `applicationHasDeploymentConfig` now as well.

**Comment by jeff-phillips-18** [comment]
@spadgett PR #1599 will remove those filters.

**Comment by jeff-phillips-18** [comment]
Updated dependencies in karam.conf.js to add new dependencies

**Comment by jeff-phillips-18** [comment]
@spadgett should I include the changes from #1625 or close this and @rhamilto can bump in #1625?

**Comment by rhamilto** [comment]
@jeff-phillips-18, in talking with @spadgett, it sounds like its best for you to cherry-pick #1625 and doing the update since this is already open.

**Comment by spadgett** [comment]
> it sounds like its best for you to cherry-pick #1625 and doing the update since this is already open.

Works for me.

I think it's a runtime error if a filter or service is defined twice? Would be good for everything to go in as one PR.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
