### PR TITLE
Bug 1387999 - Deployment strategy type should not be updated before saving strategy changes

### PR DESCRIPTION
**Pull request by jhadvig**
@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
Should we just remove the strategy from the header? Since it's the first dropdown in the form, it's clear what the strategy is. If we don't show it twice, there's no confusion about when changes persist.

**Comment by jhadvig** [comment]
@spadgett yeah,  wanted to be consistent with the header we have in BC editor. But its true that in BC editor that the only place we show the strategy is the header. 
WIll update

**Comment by jhadvig** [comment]
@spadgett update :) PTAL

**Comment by spadgett** [comment]
thanks @jhadvig 

[merge]

**Pull request merged**
