### PR TITLE
Fix canI checks that need to be wrapped in parens

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1389734
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1391879

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL, for 1.4

**Comment by spadgett** [comment]
@jwforres LGTM, but I worry we have this problem in other places

**Comment by jwforres** [comment]
yep i just found another one

**Comment by spadgett** [comment]
Looks like another one here:

https://github.com/spadgett/origin-web-console/blob/e78949acbc9a584fc4f194d87b6a13630ef62a74/app/views/browse/_replication-controller-actions.html#L1

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
