### PR TITLE
Bump origin-web-catalog to 0.0.59

### PR DESCRIPTION
**Pull request by spadgett**
https://github.com/openshift/origin-web-catalog/releases/tag/v0.0.59

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1505712
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1504973

### CODE REVIEW

**Comment by jwforres** [comment]
Looks like the dist is going to conflict with your other PR

**Comment by spadgett** [comment]
Thanks for the heads up. It looks like I have dist problems anyway. I'll wait for the other to merge and rebase.

**Comment by spadgett** [comment]
Rebased

**Pull request merged**
