### PR TITLE
Remove tasks tag from newfromtemplate page

### PR DESCRIPTION
**Pull request by jhadvig**
@spadgett PTAL

Closes https://github.com/openshift/origin-web-console/issues/286

### CODE REVIEW

**Comment by spadgett** [comment]
@jhadvig can you check if it's a problem on other pages?

**Comment by jhadvig** [comment]
@spadgett checked it and we should be safe.
The only views where we display tasks are:
- newfromtemplate
- nextsteps
- overview (and old project.html)

**Comment by spadgett** [comment]
Honestly it's a little strange we show it on newfromtemplate and not other pages. Wonder if we shouldn't just take it out. The right margin also looked wrong if you check the screenshot in #286.

I think we should either show it everywhere OR only on next steps and the overview. Leaning toward just removing it here. @jwforres

**Comment by jhadvig** [comment]
+1 .. have it everywhere could be kinda confusing. Will remove this one

**Comment by jwforres** [comment]
why does it show up here instead of going to the overview or to next steps
like we do for our other pages that are generating multiple things?

**Comment by jwforres** [comment]
what actually causes this to show up here?

**Comment by jhadvig** [comment]
@jwforres when creating app from template, on next you click on the breadcrumb with the template's name

**Comment by jwforres** [comment]
oh then yeah just take it out

**Comment by spadgett** [comment]
+1

**Comment by jhadvig** [comment]
@spadgett update

**Comment by spadgett** [comment]
Do you mind updating the commit message so it matches the actual change?

**Comment by jhadvig** [comment]
@spadgett done :)

**Comment by spadgett** [comment]
Thanks [merge]

**Pull request merged**
