### PR TITLE
Reduce tpl logic in deployment view

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Any objection to this kind of reduction?

@spadgett @jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
It's definitely an improvement. If we have this many checks, it might be better to evaluate `canI` once in the controller, though. What do you think?

**Comment by spadgett** [comment]
I'm thinking a check like this, only assigning the result to a scope var

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/addConfigVolume.js#L101

**Comment by benjaminapetersen** [comment]
I don't mind doing that, tho in kve we just decided yesterday that `canI` is better in the template @rhamilto @jwforres.  Any objections to this check?

So long as we do less object literal in the tpl, I'm good either way on the filter.

**Comment by jwforres** [comment]
i don't mind if its clear what the scope variable is for.  in KVE what was in the view had no obvious correlation back to the actual check that was happening.

**Comment by benjaminapetersen** [comment]
Cool, I will update.

**Comment by benjaminapetersen** [comment]
Updated.  Thoughts? I can condense the `ctrl` block down a bit if we don't want the `$filter('canI')` & `resourceGroup` bit expanded.

**Comment by benjaminapetersen** [comment]
rebased

**Pull request closed without merging**
