### PR TITLE
[3.5] Fix Bug 1543402 - A-MQ Components not visible in Java Console when using IE11 browser

### PR DESCRIPTION
**Pull request by akieling**
Fixes the following bug on OpenShift Enterprise 3.5:
https://bugzilla.redhat.com/show_bug.cgi?id=1543402

### CODE REVIEW

**Comment by akieling** [comment]
I incorrectly pointed to master branch but have already changed to `enterprise-3.5`.

**Comment by spadgett** [comment]
I think the tests will fail against the enterprise-3.5 branch, but we'll try. We're working on fixing our CI for older releases: https://trello.com/c/eBFQn4Vh

/lgtm

**Comment by akieling** [comment]
@spadgett is there anything I need to do to fix the tests?

**Comment by spadgett** [comment]
dist is correct

```
Verifying that checked in built files under dist match the source...
Verified.
```

@jwforres Any objections to green button merging? Integration tests fail in the enterprise-3.5 branch

**Pull request merged**
