### PR TITLE
Add option to grunt serve for disabling livereload

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/7236

### CODE REVIEW

**Comment by jwforres** [comment]
@benjaminapetersen sorry this took so long to get done :)   `grunt serve --disable-live-reload=true`

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Yay!

**Pull request merged**
