### PR TITLE
Updating .travis.yml to use xvfb, swapping PhantomJS for Firefox

### PR DESCRIPTION
**Pull request by benjaminapetersen**

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@jwforres @spadgett borrowed what I have from kve for testing with headless Firefox instead of Phantom.

**Comment by jwforres** [comment]
Hmm so this failed in Travis.  But we also need a wrapper script for Jenkins like we have for the integration tests. The wrapper needs to not fail if the xvfb display has already been started. Or the scripts need to clean up the display when they are done.

**Comment by benjaminapetersen** [comment]
Oop, forgot to add the `karma-firefox-launcher` to the config, giving it another [TEST].

A wrapper script for Jenkins...  Looking @ that.

**Comment by jwforres** [comment]
Nice, Travis looks good now. Also need to look at the Makefile that we have now since it will need to call the wrapper instead

**Comment by stevekuznetsov** [comment]
Depends on https://github.com/openshift/vagrant-openshift/pull/498

**Comment by benjaminapetersen** [comment]
Merged PR from @stevekuznetsov, [TEST] to make sure we still work in Travis, per conversation will have to wait until vagrant-openshift can get updated before things work with Jenkins.

**Comment by benjaminapetersen** [comment]
[TEST] again
- travis should run
- jenkins should fail
  - until we can update `vagrant-openshift`

**Comment by benjaminapetersen** [comment]
[TEST] again

**Comment by benjaminapetersen** [comment]
btw, while im at it switched the tests to run in FireFox even when not headless, cuz we got plenty of eyes on Chrome anyway.

**Comment by jwforres** [comment]
forcing merge on this to get around the circular dep issue with the base_amis

**Pull request merged**
