### PR TITLE
Improve warning messages for containers with non-zero exit codes

### PR DESCRIPTION
**Pull request by spadgett**
@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
so @mfojtik suggested keeping those warnings so people know their containers aren't exiting cleanly.  He fixed the ruby example so it no longer does that.

**Comment by jwforres** [comment]
Maybe we should just tack something onto the message when we know the Pod was terminating when the warning occurred?

**Comment by spadgett** [comment]
And add a "Don't show me again" link maybe?

**Comment by jwforres** [comment]
yeah sounds good

**Comment by spadgett** [comment]
Or maybe just (exit code 1) at the end is better.

**Comment by jwforres** [comment]
Yeah, 'The container ruby-helloworld did not stop cleanly when terminated
(exit code 1).'

**Comment by spadgett** [comment]
screen shot 2016-07-05 at 11 28 23 am

**Comment by jwforres** [comment]
screenshot LGTM

**Comment by spadgett** [comment]
Also adding a View Log link for crashing containers while I'm in the code. @jwforres Look OK?

openshift_web_console

**Comment by jwforres** [comment]
Yep

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
