### PR TITLE
[enterprise-3.5] Bug 1421097: Fix create secret link for build secrets

### PR DESCRIPTION
**Pull request by spadgett**
See https://bugzilla.redhat.com/show_bug.cgi?id=1421097#c11
See #1317

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
> ECONFLICT Unable to find suitable version for angular

Not seeing this locally, even if I clean assets. Flake?

[merge]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
@jwforres The enterprise-3.5 builds are picking up origin-web-common from the backed up bower components.

https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/1137/console

> origin-web-common#0.0.3 depends on angular#~1.5.11 which resolved to angular#1.5.11

**Pull request merged**
