### PR TITLE
Center pending message in bind service dialog

### PR DESCRIPTION
**Pull request by spadgett**
screen shot 2017-04-19 at 2 01 55 pm

### CODE REVIEW

**Comment by jwforres** [comment]
main change LGTM, but you've got a vendor.js change in here that you shouldn't, but for some reason Travis is ok with it...

**Comment by spadgett** [comment]
@jwforres Rebased to pick up the label selector update and got rid of the vendor diff

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
WebDriver Flake

[merge]

**Pull request merged**
