### PR TITLE
Make Jenkinsfile path a link when possible

### PR DESCRIPTION
**Pull request by spadgett**
If source repo is a GitHub repo, make the Jenkinsfile Path value a link so it's easy to see the contents of the Jenkinsfile. For non-GitHub repositories, fall back to just showing the path as before.

openshift_web_console

@jwforres PTAL
@bparees CC

### CODE REVIEW

**Comment by spadgett** [comment]
> Built dist does not match what is committed, run 'grunt build' and include the results in your commit.

Hm, I clean installed deps and ran `grunt build`. I don't see a diff. @jwforres ?

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
URI.js bump needed for `URI.joinPaths`

**Comment by spadgett** [comment]
Same error in Jenkins:

> Built dist does not match what is committed, run 'grunt build' and include the results in your commit.

**Comment by spadgett** [comment]
@jwforres I worked through my dist problem. Should be ready for review.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
