### PR TITLE
Update docs on word-break, word-break-all, swap order to favor usage of word-break

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Since we've had multiple conversations about `word-break` and `word-break-all` now, I figure its worth updating the comments a bit.  I rearranged the order to imply `word-break` should be the priority, and attempted to update the text with a bit of the reasoning.   

@sg00dwin @rhamilto @spadgett thoughts?

### CODE REVIEW

**Comment by rhamilto** [comment]
👍

**Comment by spadgett** [comment]
Thanks @benjaminapetersen, looks good. Will wait for 1.5 to merge.

**Comment by sg00dwin** [comment]
+1

**Comment by spadgett** [comment]
@benjaminapetersen needs rebase, but otherwise looks good

**Comment by benjaminapetersen** [comment]
rebased, but digging around in the `dist` file, couple things look peculiar, though I did a full hack clean, install, build. hmm.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
