### PR TITLE
Warn when editing YAML did not change the object

### PR DESCRIPTION
**Pull request by spadgett**
Show a warning and stay on the edit YAML page when no edits were applied. This can happen when trying to add a property that is not recognized or when misspelling a field name.

See #1221

### CODE REVIEW

**Comment by jwforres** [comment]
what happens if someone modifies something else in etcd between the time Edit YAML is opened and when you saved?  resourceVersion isn't per object

**Comment by spadgett** [comment]
Just tested: it still works.

We're checking that the resource version hasn't changed at all, which seems to be the case always if I add an unrecognized property.

**Comment by spadgett** [comment]
@jwforres travis is complaining about dist, and I'm not sure why

**Comment by jwforres** [comment]
cleared the caches and told it to rebuild, if that doesn't work maybe try cleaning your deps?  its vendor.js its complaining about, maybe some dependency has changed.

**Comment by spadgett** [comment]
Updated to fix dist

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
