### PR TITLE
Bump origin-web-common to 0.0.51

### PR DESCRIPTION
**Pull request by spadgett**
Contains changes needed for #1906 and #1932

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by jeff-phillips-18** [comment]
Can we bump to angular patternfly 4.7.1 as well?

**Comment by spadgett** [comment]
> Can we bump to angular patternfly 4.7.1 as well?

Looks like @benjaminapetersen has that as part of #1988. Do you mind using that PR?

**Comment by jeff-phillips-18** [comment]
I can wait but https://github.com/openshift/origin-web-console/pull/1966 is dependent on it.

**Comment by spadgett** [comment]
@jeff-phillips-18 Any objections? I ask because this PR is blocking #1932 

I think #1988 is about ready. I'll work with @benjaminapetersen to get that in.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
