### PR TITLE
Watch projects on project list page

### LINKED ISSUE #56: Deleted projects never disappear from view
Steps to reproduce:

1) Log into OpenShift Console
2) Create new project with some default values
3) Go back to Home
4) Delete the project you'd just created
5) Status of the project shows marked for deletion
6) Item does not disappear on its own when it's deleted; console needs a refresh

screenshot4

### PR DESCRIPTION
**Pull request by spadgett**
Requires https://github.com/openshift/origin/pull/9204 before we can merge

Fixes #56
/cc @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
change LGTM

**Comment by spadgett** [comment]
@jwforres Please have another look. I verified @deads2k fix, which is good. I also removed the special click handler on the logo since I don't think we need it anymore.

**Comment by jwforres** [comment]
@spadgett tests are failing now, need to mock out DataService.watch instead of DataService.list

**Comment by jwforres** [comment]
otherwise LGTM

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
