### PR TITLE
Replace osc-key-values editor on edit/buildConfig

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Another round of kvc fun.

screen shot 2016-07-12 at 5 38 13 pm

@jwforres @spadgett @rhamilto

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Btw, looking into the other instance for image-source-paths on this page.  Need to data to make it appear so I can swap it.

**Comment by jwforres** [comment]
lets change both of them in this page in the same PR, would be weird to have two different ones show up in the same form when they are both editing env.  The existing change LGTM just let me know when you get the other one done

**Comment by benjaminapetersen** [comment]
Will fix https://github.com/openshift/origin/issues/8048

**Comment by benjaminapetersen** [comment]
@jwforres updated both instances of the editor.
@jhadvig ping just in case you wanna take a look too.

**Comment by jwforres** [comment]
[merge]

but you are probably going to get a merge conflict on bower.json and vendor.js on your other PR now

**Comment by benjaminapetersen** [comment]
@jwforres yeah, figured. ill watch this and rebase.

**Comment by benjaminapetersen** [comment]
that was fast.

**Comment by jhadvig** [comment]
Looks great @benjaminapetersen ! :+1:

**Pull request merged**
