### PR TITLE
Make strings translatable on the web console

### PR DESCRIPTION
**Pull request by tagoh**
resubmit PR because the web console part is separate from origin. the original PR was https://github.com/openshift/origin/pull/4332 for the reference.

### CODE REVIEW

**Comment by xiaoping378** [comment]
@tagoh Are you working on this ?

**Comment by xiaods** [comment]
@xiaoping378 we are working on it. let work together?

**Comment by xiaoping378** [comment]
@xiaods 不干这行了，现在恐怕没时间了。你可以去群里问问，以前有人干过，加我微信 "yiyemeishui"

**Comment by xiaods** [comment]
out of date. please close it.

**Comment by spadgett** [comment]
Closing as this repo is now only for bug fixes to previous 3.x release. New development is happening at openshift/console.

/close

**Pull request closed without merging**
