### PR TITLE
Don't collapse boolean attributes in minified HTML

### PR DESCRIPTION
**Pull request by spadgett**
@jwforres Opinions on this change? I think it could avoid problems like 

https://bugzilla.redhat.com/show_bug.cgi?id=1390499

in the future.

https://github.com/kangax/html-minifier#options-quick-reference
http://perfectionkills.com/experimenting-with-html-minifier/#collapse_boolean_attributes

### CODE REVIEW

**Comment by jwforres** [comment]
have tried running with the change to see how big of a diff it creates for us?

**Comment by jwforres** [comment]
have you tried running grunt build i mean

**Comment by spadgett** [comment]
Added dist. It's not too large.

The changes from `spellcheck="false"` to just `spellcheck` by the minifier without this setting also seem wrong :(

**Comment by jwforres** [comment]
honestly i think we should merge this

**Comment by spadgett** [comment]
Rebased

**Comment by benjaminapetersen** [comment]
Yeah, looks like thats probably a good idea...

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
WebDriver flake [merge]

**Pull request merged**
