### PR TITLE
Adjustments so Safari maintains equal min-height on deployment tiles

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes bug https://bugzilla.redhat.com/show_bug.cgi?id=1389640

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jwforres @spadgett  PTAL

**Comment by spadgett** [comment]
@sg00dwin you'll need to call `hack/clean-assets.sh`, `hack/install-assets.js`, and `grunt build` again since a dependency changed.

**Comment by jwforres** [comment]
if you want to save time, in this case a bower install should be sufficient

**Comment by sg00dwin** [comment]
ok, is updated

**Comment by sg00dwin** [comment]
screen shot 2016-10-28 at 5 14 02 pm

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
