### PR TITLE
Update deployImage directive to use getPreferredVersion

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Depends on [common 251](https://github.com/openshift/origin-web-common/pull/251)

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM, just needs the comment removed once common is updated

**Comment by benjaminapetersen** [comment]
rebased.
`imagestreamimages` so removing [WIP]

**Comment by jwforres** [comment]
@benjaminapetersen this one needs rebasing now

**Comment by benjaminapetersen** [comment]
dupe, wups.

**Pull request closed without merging**
