### PR TITLE
Bug 1753601: Correctly map kind to resource

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1753601

/assign @rhamilto

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Review by rhamilto — COMMENTED** [review]
/lgtm

**Comment by dobbymoodge** [comment]
/retest 

note that this will probably fail at the `/bin/yum install ./google-chrome-stable_current_x86_64.rpm -y` step. As of right now, the Chrome RPM at https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm appears bugged - I found the `yum` process hung while the underlying `rpm` was running one of the install scripts; it was in this block:

```
  if [ "$?" -eq "0" ]; then
    # Note, if this is run during the package install, it will fail because rpm
    # can't recursively run rpm, but it should work when run later as part of
    # the installed cron job (and probably nothing needs the new keys before
    # then).
    rpm -e --allmatches ${KEY_PACKAGE} >/dev/null 2>&1 || return
  fi
```

I don't know if there's a way to pull down an older, known-working RPM. I'll see if I can figure out how to file bugs against Chrome packaging.

**Comment by dobbymoodge** [comment]
That test and `rpm` call exist in older versions of the RPM as well, as far as I can tell, so maybe it's triggering a new bug in RPM?

**Pull request merged**
