### PR TITLE
Warn users when resource has changed when editing YAML

### LINKED ISSUE #142: Editing deploy config twice via `Edit YAML` option in immediate succession results in a confusing error
screen shot 2016-07-08 at 12 02 01 pm

To reproduce:

* Browse to a deployment config and choose `Edit YAML` from the `Actions` menu in the upper right
* Edit an env var
* Click `Save`
* Click `Actions` and `Edit YAML` again
* Make an additional edit to an env var
* Click `Save`
* Notice the resulting error

I notice the error isn't thrown once the `Deploy` button is re-enabled following the deployment resulting from the first edit. 

@benjaminapetersen

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #142 by warning users when something has changed since they started editing. @jwforres PTAL

openshift_web_console

### CODE REVIEW

**Comment by spadgett** [comment]
Going to change the message to say "copy any changes you've made"

**Comment by liggitt** [comment]
what? no three-way diff showing original, edited, and new?

**Comment by spadgett** [comment]
I was actually thinking about it.....

http://benkeen.github.io/ace-diff/

**Comment by jwforres** [comment]
three-way diff in a modal dialog though?  doesn't seem like we would have the space for that

**Comment by jwforres** [comment]
[merge] this for now, you can open an enhancement issue to look at the diff later

**Comment by liggitt** [comment]
> three-way diff in a modal dialog though? doesn't seem like we would have the space for that

I guess you wouldn't need a three way diff... building a patch between the original content and the edited content, then applying it to the new content, indicating any merge conflicts would be sufficient

**Comment by spadgett** [comment]
If we made it a separate page instead of a dialog, there'd be more room.

https://github.com/openshift/origin/issues/6845#issuecomment-176855327

**Comment by jwforres** [comment]
I'm ok with that

**Pull request merged**
