### PR TITLE
Changing default icon for templates to fa-clone

### LINKED ISSUE #1673: Inconsistent default icon for templates between old and new experience
In the old experience we used fa-clone, in the new experience its using fa-cubes which we usually used for images not templates.  See https://github.com/openshift/origin-web-console/pull/1382/files#r120115098

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1673

Bumps common to v0.0.38, catalog to v0.0.26

screen shot 2017-06-23 at 1 25 10 pm

### CODE REVIEW

**Comment by rhamilto** [comment]
@jwforres, this is ready for review.

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@rhamilto buried in the full console output, looks like you got a dist on
main.css

**Comment by jwforres** [comment]
yeah travis failed on it as well

**Comment by rhamilto** [comment]
[merge]

**Comment by jwforres** [comment]
just killed the merge that was already running since it was on the old commit, just to make sure rosie kicks it again [merge]

**Pull request merged**
