### PR TITLE
Update key-validator regexp for key-value-editor

### PR DESCRIPTION
**Pull request by jhadvig**
Backport of https://github.com/openshift/origin-web-console/pull/3052

@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
@jhadvig Looks like Jenkins doesn't like the dist files.

**Comment by jhadvig** [comment]
About to re-generate them

**Comment by jhadvig** [comment]
@spadgett PR updated.PTAL

**Comment by spadgett** [comment]
```
[INFO] Verifying that checked in built files under dist match the source...
[FATAL] Built /dist does not match what is committed, run 'grunt build' and include the results in your commit.
```

Interestingly, travis didn't complain

**Comment by jhadvig** [comment]
Will update ASAP

**Pull request merged**
