### PR TITLE
[enterprise-3.11] Bug 1633285 - No secrets dropdown in buildconfig edit page if any of the secrets has no data

### PR DESCRIPTION
**Pull request by jhadvig**
@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

We should hold this until 3.11 is open for z-stream fixes.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
Jenkins didn't run. Looks like we need https://github.com/openshift/aos-cd-jobs/pull/1636

**Comment by jhadvig** [comment]
@spadgett can we remove the hold tag ?

**Comment by spadgett** [comment]
> @spadgett can we remove the hold tag ?

We need to figure out why jenkins was skipped. Not all tests have run :(

**Comment by spadgett** [comment]
Needs openshift/release#2262 to enable Jenkins

**Comment by spadgett** [comment]
@jhadvig It looks like cluster up is failing in our tests. Any channce you can investigate?

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/clusterup/coreinstall/kubeapiserver.KubeAPIServerStartConfig.MakeMasterConfig(0xc420c59080, 0x24, 0xc4209d2240, 0x6, 0x6, 0x4758f60, 0xc420438160, 0xc420ba5080, 0x3f, 0x0, ...)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/coreinstall/kubeapiserver/config.go:91 +0xbea
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).makeMasterConfig(0xc420748a00, 0xc4207aef30, 0x1, 0x0, 0x4717fe0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:365 +0x530
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).BuildConfig(0xc420748a00, 0xc420000100, 0xc421073800, 0xc4210738e0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:278 +0xf4f
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).StartSelfHosted(0xc420748a00, 0x4717f60, 0xc42000e018, 0x20, 0xc421073b00)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/run_self_hosted.go:127 +0x43
github.com/openshift/origin/pkg/oc/clusterup.(*ClusterUpConfig).Start(0xc420748a00, 0x4717f60, 0xc42000e018, 0x0, 0x4)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/up.go:473 +0x135
github.com/openshift/origin/pkg/oc/clusterup.NewCmdUp.func1(0xc420748c80, 0xc420fce2a0, 0x0, 0x3)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/clusterup/up.go:112 +0xe7
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420748c80, 0xc420fce1e0, 0x3, 0x3, 0xc420748c80, 0xc420fce1e0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:757 +0x2c1
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4209cfb80, 0xc42000e020, 0xc4209cfb80, 0xc42022d4a0)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:843 +0x334
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4209cfb80, 0x2, 0xc4209cfb80)
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:791 +0x2b
main.main()
	/tmp/openshift/build-rpms/rpm/BUILD/origin-3.11.0/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:42 +0x334
```

**Comment by jhadvig** [comment]
@spadgett on it !

**Pull request merged**
