### PR TITLE
Add "Cancel deployment" action to overview

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1365666

openshift_web_console

openshift_web_console

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
im just trying to decide if it needs the full "Cancel deployment" text for the link, what if it just said "cancel"  lower case so it doesnt seem so visually important and flows better with the previous text ?

**Comment by jwforres** [comment]
otherwise this LGTM

**Comment by spadgett** [comment]
Here it is with lowercase cancel for comparison

openshift_web_console

**Comment by jwforres** [comment]
i definitely prefer the cancel instead of cancel deployment, could go
either way on Cancel vs cancel i think, will leave that up to you

**Comment by spadgett** [comment]
Slight preference for Cancel so it's consistent with other action links in the web console

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
