### PR TITLE
Clean up overview directives

### PR DESCRIPTION
**Pull request by spadgett**
The `service-group` directive currently takes 16 (!) attributes, almost all of them unchanged from the parent controller. Thoughts on this change? I think I've convinced @benjaminapetersen :)

If we agree this makes sense, I can make the same change to the `overview-service` directive.

@jwforres 

- [x] Update `overview-service` directive
- [x] Update `service-group` directive name to make it clear it's only for the overview

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Yup, issues with shared `$scope` aside, I think eliminating 80 lines of code is definitely a good thing! :smile:

Seems like this is a good refactor step to take here.

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Wait timed out flake, [merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
```
Running "protractor:chrome" (protractor) task
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
>> /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
>>       throw error;
>>             ^
>> Error: Timed out waiting for the WebDriver server at http://172.18.2.59:45811/wd/hub
>>     at Error (<anonymous>)
>>     at onResponse (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:87:11)
>>     at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:42:21
>>     at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
>>     at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/index.js:145:7)
>>     at ClientRequest.emit (events.js:95:17)
>>     at Socket.socketErrorListener (http.js:1603:9)
>>     at Socket.emit (events.js:95:17)
>>     at net.js:441:14
>>     at process._tickCallback (node.js:448:13)
Fatal error: protractor exited with code: 8
```

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Wait timed out flake again, [merge]

**Pull request merged**
