### PR TITLE
Change "Link Service" to "Group Service"

### PR DESCRIPTION
**Pull request by spadgett**
@jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
openshift_web_console

**Comment by spadgett** [comment]
openshift_web_console

**Comment by jwforres** [comment]
doesn't sound as good but it will at least eliminate the confusion,  any feedback @ncdc before we merge this

**Comment by jwforres** [comment]
cc @sspeiche

**Comment by ncdc** [comment]
👍

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
