### PR TITLE
[WIP] Add ng-aria

### PR DESCRIPTION
**Pull request by benjaminapetersen**
`<key-value-editor>` accessibility research spawned some curiosity.  WIP as I have only read up and installed it, still tinkering.

@spadgett feel like I remember you mentioning this in the past.  I'll look in the origin repo and see if there was an issue or something.

@jwforres 

(not proposing to merge this week)

### CODE REVIEW

**Comment by spadgett** [comment]
+1 looks like a good change (for post 1.3)

**Comment by jwforres** [comment]
yep seems reasonable to me

**Comment by benjaminapetersen** [comment]
The checklist for accessibility originally had this, per @spadgett on [this comment](https://github.com/openshift/origin/issues/5988#issuecomment-160721193).

**Comment by benjaminapetersen** [comment]
[test]
Rebased this one.  Working through the UI everything seems in order, no funny business yet.
@jwforres @spadgett

**Comment by jwforres** [comment]
looking back at the list of what it adds, my biggest concerns are with ngClick and ngDblClick because its automatically adding tabindex to things.  I don't think we want that.  Example, it would make our clickable tiles be in the keyboard tabindex, but we have links within the tiles which link to the same thing.  We don't want both the tile and the link to be in the tabindex.

Unfortunately it doesn't look like you can tell it to ignore individual instances of ng-click and instead have to globally turn off of those particular features, see https://docs.angularjs.org/guide/accessibility

**Comment by liggitt** [comment]
you *really* don't want to get in the business of managing tabindex if you can at all help it

**Comment by benjaminapetersen** [comment]
Agreed on managing tabindex, lets not do that.

So I believe setting `tabindex="-1"` will basically act as a "ignore" for ng-Aria (and [eliminates its tab focus ability](https://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute)).  If we hate that (I kinda do), we can make an attribute directive `<aria-ignore>` that could set that attribute for us behind the scenes (and we won't forget why we set it) on whatever element we use it with. 

I can add that to this PR and do a round of lots of tabbing through the UI.  Feel free to chime in with any other known tab disasters :)

**Comment by benjaminapetersen** [comment]
[Some chatter @ the angular repo about this issue](https://github.com/angular/angular.js/issues/14602).

**Comment by jwforres** [comment]
@liggitt are you suggesting we should let ng-aria manage it for us, or that
we shouldn't let ng-aria muck with the tabindex?

**Comment by liggitt** [comment]
The latter

**Comment by jwforres** [comment]
its not just the tabindex, its also adding a keypress event and
role=button.  I think I would be more comfortable just disabling the
ngClick support altogether, there are three flags you disable, the details
were in that developer guide i linked before

**Comment by benjaminapetersen** [comment]
Works for me, I'll update this.

**Comment by benjaminapetersen** [comment]
Added `$ariaProvider.config()`, turned off a couple things.  Inspecting source I can def see the additional `aria-*` attributes added to elements.  Tabbing around the interface (before enabling, after enabling) it seems seamless.  So far I haven't found any quirky interactions.

**Comment by benjaminapetersen** [comment]
looks like a flake, [TEST]

**Comment by spadgett** [comment]
> ECONFLICT Unable to find suitable version for angular

**Comment by benjaminapetersen** [comment]
Hmm. neat. will fix.

**Comment by benjaminapetersen** [comment]
matched `1.3.20` w/the other angular core modules, should be good to go this time. 
[TEST]

**Comment by benjaminapetersen** [comment]
Fail on:
```
PhantomJS 2.1.1 (Linux) ERROR
  Error: [$injector:modulerr] Failed to instantiate module openshiftConsole due to:
  [$injector:modulerr] Failed to instantiate module ngAria due to:
  [$injector:nomod] Module 'ngAria' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
  http://errors.angularjs.org/1.3.20/$injector/nomod?p0=ngAria
```
Hmm. angular-aria installed, in `bower.json`, in `index.html`, dependency in `app.js`...
[TEST] again Rosie while I go fish around...

**Comment by benjaminapetersen** [comment]
rebased

**Comment by benjaminapetersen** [comment]
rebased, includes the config block:
```javascript
  .config(function($ariaProvider) {
    $ariaProvider.config({
      tabindex: false,
      bindRoleForClick: false,
      bindKeydown: false
    });
  })
```

**Comment by benjaminapetersen** [comment]
tinkering with tests...

**Comment by benjaminapetersen** [comment]
rebased

**Pull request closed without merging**
