### PR TITLE
Do not allow binding to an application when pod_presets is false

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Depends on origin-web-common release with openshift/origin-web-common#167

### CODE REVIEW

**Comment by spadgett** [comment]
@jeff-phillips-18 Looks like a dist mismatch

**Comment by jeff-phillips-18** [comment]
Added commit to bump origin-web-common to 0.0.52.

Removed WIP status.

**Comment by spadgett** [comment]
@jeff-phillips-18 Just confirming that creating the binding from the service instance row still works. I thought we had blocked that when pod_presets was false previously

**Comment by jeff-phillips-18** [comment]
@spadgett you are able to create the binding with pod_presets false. Not sure if this was in error before, but its working now ;)

**Comment by jeff-phillips-18** [comment]
`  ENABLE_TECH_PREVIEW_FEATURE: {
    // Enable the new landing page and service catalog experience
    service_catalog_landing_page: true,
    // Set to `true` when the template service broker is enabled for the cluster in master-config.yaml
    template_service_broker: false,
    pod_presets: false
  },
`
image

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Flake #2016

[merge]

**Pull request merged**
