### PR TITLE
Remove margin that causes errant spacing when build icon and message not shown

### PR DESCRIPTION
**Pull request by sg00dwin**
and prevent aggressive wrapping of deployment message.

**Before changes**
screen shot 2017-07-11 at 2 16 03 pm

**After changes**
screen shot 2017-07-11 at 2 26 21 pm

### CODE REVIEW

**Comment by sg00dwin** [comment]
pr updated

**Comment by spadgett** [comment]
@sg00dwin Need to fix dist files (try `bower install && grunt build`)

**Comment by sg00dwin** [comment]
@spadgett updated pr

**Comment by spadgett** [comment]
[merge][severity: bug]

**Pull request merged**
