### PR TITLE
base64-encode state param to work around fragment weirdness

### PR DESCRIPTION
**Pull request by liggitt**
resolves the angular-related aspect of https://github.com/openshift/origin/issues/12044

TODO:
- [x] refactor existing utilities to be shared
- [x] test across browsers

### CODE REVIEW

**Comment by liggitt** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
LGTM although travis is complaining about the dist

**Comment by liggitt** [comment]
[test]

**Comment by liggitt** [comment]
weird, cleaning/installing/building shows no diff for me... let's see what Jenkins thinks

**Comment by liggitt** [comment]
jenkins was happy, [merge]

**Pull request merged**
