### PR TITLE
Adopt new service catalog resource names

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/y1lbFrbp

Instance -> ServiceInstance
Binding -> ServiceInstanceCredential

Bump origin-web-common to 0.0.56
Bump origin-web-catalog to 0.0.45

Depends On:

https://github.com/openshift/origin/pull/16150
https://github.com/openshift/origin-web-common/pull/182
https://github.com/openshift/origin-web-catalog/pull/426

@pmorie @jpeeler FYI

### CODE REVIEW

**Comment by spadgett** [comment]
This doesn't yet remove alpha prefixes since that's not in service-catalog 0.0.17 and therefore should not be in openshift/origin#16150

**Comment by spadgett** [comment]
cc @jmontleon

**Comment by spadgett** [comment]
@jpeeler @jeff-phillips-18 FYI, I've been able to validate the name changes with openshift/origin#16150

**Comment by spadgett** [comment]
Service catalog rebase has merged in origin.

**Comment by spadgett** [comment]
To test with the latest service catalog.

* Build latest `oc` from master
* `docker pull openshift/origin:latest`
* `docker pull openshift/origin-service-catalog:latest`
* `oc cluster up --version=latest --service-catalog`

**Comment by dtaylor113** [comment]
Cannot find any instances of:
```
'bindings'
"instances"
"Instance"
```
Searched in ```/app``` using both single and double quotes.

**Comment by spadgett** [comment]
Rebased and updated with dist. Includes catalog and common version bumps.

**Comment by spadgett** [comment]
[test]

**Comment by benjaminapetersen** [comment]
First pass looks good.  Working on running locally now. Deleted all my images & containers, but pulling `origin:latest` didn't seem to get the latest catalog images. My `CatalogService.SERVICE_CATALOG_ENABLED` is false due to the `APIService.apiInfo()` checks on all the catalog resources.

**Comment by spadgett** [comment]
[merge][severity: blocker]

**Comment by spadgett** [comment]
@benjaminapetersen You also need to run `docker pull openshift/origin-service-catalog` to get the latest service catalog image

**Pull request merged**
