### PR TITLE
Let users edit app label directly for "add to project"

### LINKED ISSUE #1422: Not obvious that the app label can be changed
The app label in the UI is not modifiable and this is a bug (it should be) as it is from the CLI.

image

As explained by @bparees in an email:

> here's the label applying logic for new-app:
> 
> for non-template deployments:
> 
> 1) if the user provides labels on the command line, assign those labels
> 2) assign the default app=name to all objects, unless (1) already set the "app" label.
> 
> for template deployments:
> 
> 1) if the template defines labels, assign them
> 2) if the user provides labels on the command line, assign those labels (possibly overwriting values from (1)
> 3) assign the default app=name to all objects unless (1) or (2) already set the "app" label or any of the objects otherwise already has an app label defined (in which case we don't set it on any object).
> 
> So there should always be *an* app label available unless your template explicitly defines the app label on only a subset of objects in the template.

### PR DESCRIPTION
**Pull request by spadgett**
Prefill the label values instead of having a separate "system labels"
section that is read-only. Fixes a usability bug where it wasn't obvious
the app label could be overridden.

Fixes #1422

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres opinion on this change?

**Comment by spadgett** [comment]
@bparees This change would let users optionally remove template labels from generated objects when instantiating templates from the web console. Is that a problem?

It might be possible to make the name readonly, but let users edit the value directly if we don't want users to remove the labels altogether.

**Comment by bparees** [comment]
> @bparees This change would let users optionally remove template labels from generated objects when instantiating templates from the web console. Is that a problem?

@spadgett no, i don't think so.  Especially since this has no effect when a user instantiates a template via the service catalog provision flow, right?

**Comment by spadgett** [comment]
> Especially since this has no effect when a user instantiates a template via the service catalog provision flow, right?

It won't, but users can still instantiate templates directly from YAML in the web console.

**Comment by bparees** [comment]
> It won't, but users can still instantiate templates directly from YAML in the web console.

sure, i'm just noting that the one case where we might rely on labels at all is in the provision flow, so if you're not changing that, i don't think we care.

**Comment by spadgett** [comment]
@jwforres PTAL

I need to rebuild to fix the scripts.js conflict, but should be ready for review

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
