### PR TITLE
Show the output of successful dependency installations

### PR DESCRIPTION
**Pull request by stevekuznetsov**
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
[test]

@jwforres

**Comment by jwforres** [comment]
Will definitely help debugging what changes between successful test runs and failed ones
cc @spadgett

**Comment by jwforres** [comment]
i'm fine merging this whenever you are @stevekuznetsov

**Comment by stevekuznetsov** [comment]
[merge]

**Comment by stevekuznetsov** [comment]
@jwforres looks like @openshift-bot doesn't respect mah authoritah in this repo... can you merge?

**Comment by spadgett** [comment]
@stevekuznetsov just this once...

**Pull request merged**
