### PR TITLE
Utilizing openshift-logos-icon dependency

### PR DESCRIPTION
**Pull request by rhamilto**
Instead of local copy.

### CODE REVIEW

**Comment by jwforres** [comment]
were we not using the dist/styles/fonts/openshift-logos-icon.eot  font file at all? looks like it was completely removed from the final dist output

did you run the grunt server in the dist mode to see if the logos still loaded correctly on all the browsers?

**Comment by rhamilto** [comment]
> were we not using the dist/styles/fonts/openshift-logos-icon.eot font file at all? looks like it was completely removed from the final dist output

No as the .eot is for IE6-8 and IE9 in compatibility mode.

> did you run the grunt server in the dist mode to see if the logos still loaded correctly on all the browsers?

I did.  But let me double check as you asking the question has cast doubt.  ;-)

**Comment by jwforres** [comment]
Ok :)  the changes LGTM but I want to hold this till monday given the risk

**Comment by rhamilto** [comment]
> I did. But let me double check as you asking the question has cast doubt. ;-)

Double check is good.

screen shot 2017-06-20 at 1 34 04 pm

screen shot 2017-06-20 at 1 34 55 pm

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
