### PR TITLE
Remove calls to AlertMessageService.getAlerts() / clearAlerts()

### PR DESCRIPTION
**Pull request by spadgett**
These methods are no longer needed since we are now showing toast notifications for alerts that cross page transitions.

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM but should wait for the other toast PRs to all merge before tagging this one

**Comment by jwforres** [comment]
unless all the ones that removed refs to AlertsService are already merged

**Comment by spadgett** [comment]
#1677 is the last one

**Comment by jwforres** [comment]
should be good to [merge] now

**Pull request merged**
