### PR TITLE
Global tech preview indicator for service catalog

### LINKED ISSUE #1699: Need a tech preview indicator when service catalog is enabled

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1699

Following the design direction set by the page-level "Technology Preview" badge, how about an orange bar above the navbar?  Exact message wording to be determined.

screen shot 2017-06-15 at 10 27 00 am
screen shot 2017-06-15 at 10 26 23 am

screen shot 2017-06-15 at 10 29 02 am
screen shot 2017-06-15 at 10 29 39 am

### CODE REVIEW

**Comment by rhamilto** [comment]
@sspeiche, @jwforres says to ping you on this...

**Comment by sspeiche** [comment]
Seems fine to me. I could see someone getting annoyed with it and perhaps wanting to dismiss it.

As far as the wording, I think the wording is fine if the text linked out to somewhere that described what was tech preview. Though I could see 2 different things being tech preview: 1. the UI/UX and 2. the underlying service catalog (and brokers). It might be handy to know when it is one or both.

**Comment by rhamilto** [comment]
> Seems fine to me. I could see someone getting annoyed with it and perhaps wanting to dismiss it.

Per @jwforres, we sort of want it to be annoying as we will not be supporting service catalog in tech preview and do not want it to be overlooked.

> As far as the wording, I think the wording is fine if the text linked out to somewhere that described what was tech preview. Though I could see 2 different things being tech preview: 1. the UI/UX and 2. the underlying service catalog (and brokers). It might be handy to know when it is one or both

Adding a link is easy.  What it links to is the hard part.  Who is to create the documentation and where does it live?

**Comment by rhamilto** [comment]
Gonna go ahead and request review and merge on this with the understanding we'll possibly add a follow on to add a link.

**Comment by jwforres** [comment]
LGTM but don't think this qualifies for a blocker, would rather hold it till monday

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
