### PR TITLE
[enterprise-3.6] Bug 1473601 - Fix form validation for deploy image

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1473601

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
It's doing the right thing branch-wise now but looks like it failed on a
vendor dist

**Comment by spadgett** [comment]
[merge][severity: blocker]

**Pull request merged**
