### PR TITLE
Handle binary files when creating generic secrets

### LINKED ISSUE #2896: Handle Binary Content for Generic Secrets
Related #2879 

In Create Generic Secret we are storing key-pair values in `secret.stringData = data.genericKeyValues.data;`.   Since the 'value' can be uploaded from a file which has base64, we need to store those values in `secret.data` as opposed to `secret.stringData`.

### PR DESCRIPTION
**Pull request by spadgett**
/assign @dtaylor113 

Closes #2896

### CODE REVIEW

**Comment by dtaylor113** [comment]
I uploaded a file with non-printable characters, and the Ace editor is hidden:
image

However, could we display help text indicating that the file contains non-printable chars, so the editor is unavailable?  Similar to how we do it in Secret Details:
image

**Comment by spadgett** [comment]
> However, could we display help text indicating that the file contains non-printable chars, so the editor is unavailable?

Yeah, my first implementation had that, and I actually took it out since I thought it worked better without. But I don't have a strong opinion.

@ncameronbritt thoughts?

**Comment by dtaylor113** [comment]
> Yeah, my first implementation had that, and I actually took it out since I thought it worked better without. But I don't have a strong opinion.

IMO we need it, it looks like a bug when there may be multiple items, but some do not show the editor:
image

@ncameronbritt

**Comment by spadgett** [comment]
@dtaylor113 I spoke to @ncameronbritt, and we agreed to add the message. PTAL

**Pull request merged**
