### PR TITLE
Improve attach storage and add config file validation

### PR DESCRIPTION
**Pull request by spadgett**
Correctly validate paths on the client when checking key/path items for a config map or secret volume.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1397788
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1397789

@jwforres PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
openshift_web_console

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
hold, found a small bug

**Comment by spadgett** [comment]
Updated to fail validation on values that are exactly `..`

@jwforres please take another look

**Comment by spadgett** [comment]
Added volume name validation as well while in the code.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
