### PR TITLE
bump origin-web-common to 3.9.0-alpha.6

### LINKED ISSUE #2646: Getting Error notification "the API version in the data (v1) does not match the expected API version (project.openshift.io/v1)"
I just tried the 'Create from URL' scenario  below using a clean console master branch which referred to `origin-web-common 3.9.0-alpha.4` and it worked fine.  I then changed console to use `origin-web-common 3.9.0-alpha.5` which has a number of commits since `-alpha.4`.  I believe the commits between `origin-web-common 3.9.0-alpha.4` and `alpha.5` are causing the 'Create from URL' issue below.

Using: docker v.1.12.6, oc  v.3.7.0-rc.0+fc8725b-108-dirty, go 1.8.3, latest docker images (`docker pull openshift/origin:latest & docker pull openshift/origin-service-catalog:latest`).

`oc cluster up --version=latest --service-catalog=true`

I enter the following url: `https://localhost:9000/dev-console/create?imageStream=nodejs&imageTag=4&name=nodejs&sourceURI=https:%2F%2Fgithub.com%2Fopenshift%2Fnodejs-ex.git&sourceRef=master&contextDir=%2F` 

and get to this point.  Clicking on [Create] project results in the following error notificaiton:

image

`the API version in the data (v1) does not match the expected API version (project.openshift.io/v1)` ?

This may be causing the Jenkins Integration Test failures in PR: #2610

### PR DESCRIPTION
**Pull request by benjaminapetersen**
- depends on the actual version bump [common 278](https://github.com/openshift/origin-web-common/pull/278)
- Fixes #2646 (tested & verified)
- relevant to PR #2610

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
@dtaylor113 
@jwforres @spadgett

**Comment by benjaminapetersen** [comment]
tests passed, should be good in a minute @dtaylor113

**Comment by dtaylor113** [comment]
> tests passed, should be good in a minute @dtaylor113

Looks like Travis passed.  I did see Jenkins pass the web console tests earlier, but it seems to be running them again(?).

**Pull request merged**
