### PR TITLE
Show pod metrics donut to right of sparkline

### LINKED ISSUE #912: Millicore Doughnut Seems Out-of-Place on Metrics Overview
In the metrics overview, the CPU millicore doughnut takes up a huge amount of screen real-estate and breaks up the flow of the page:
cores

### PR DESCRIPTION
**Pull request by spadgett**
Place the pod metrics donut to the right of the sparkline at wider screen widths to make better use of the screen space. At mobile, still place the donut above the sparkline.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1387286
Fixes #912 

screen shot 2016-12-05 at 8 29 49 am

@jwforres PTAL
@smarterclayton @stevekuznetsov @jupierce CC

### CODE REVIEW

**Comment by jwforres** [comment]
what does it look like with the network metrics that don't have a donut, i assume the sparklines are all the same width?

**Comment by spadgett** [comment]
@jwforres 

screen shot 2016-12-05 at 12 23 30 pm

**Comment by jwforres** [comment]
hmm the horizontal line makes network look like a part of the same section as cpu

**Comment by spadgett** [comment]
> the horizontal line makes network look like a part of the same section as cpu

Let me see what I can do.

**Comment by spadgett** [comment]
@jwforres How about this?

screen shot 2016-12-05 at 12 47 08 pm

**Comment by spadgett** [comment]
Hold, need to make some updates for the monitoring page, which has the sidebar

**Comment by spadgett** [comment]
Updated for the monitoring page

**Comment by jwforres** [comment]
Thats definitely better although i think i would reduce the spacing between Network and the bar, probably half as much.  Its definitely larger than the space between the numbers and the bars on the other two.

**Comment by jwforres** [comment]
I can't decide but I wonder if it would look better to move the number information directly to the right of the header, like CPU - 500[etc]

and then match the header font size and number font size

**Comment by spadgett** [comment]
We do show small "Container Metrics" or "Pod Metrics" text by the header if there is more than one container, although we could move that.

**Comment by spadgett** [comment]
> I can't decide but I wonder if it would look better to move the number information directly to the right of the header, like CPU - 500[etc]

openshift_web_console

**Comment by spadgett** [comment]
Or if we just bump the font size for the metric label

openshift_web_console

**Comment by jwforres** [comment]
yeah inline at the same font size it looks weirdly likes its part of the header, dont like it :-\

I can't decide on the larger header size, feels a little overwhelming, @ajacobs21e opinion?

**Comment by stevekuznetsov** [comment]
Maybe the "X available" could be on top of the doughnut and "in use" could come after the "x millicores" inside of the doughnut?

**Comment by stevekuznetsov** [comment]
As both are only set up if quota is on, right?

**Comment by spadgett** [comment]
Here is the Patternfly style for reference:

http://www.patternfly.org/pattern-library/cards/utilization-trend-card/#/api

**Comment by jwforres** [comment]
Eh, maybe just stick with the smaller header then.

**Comment by spadgett** [comment]
Tightened the spacing under the Network header

screen shot 2016-12-05 at 2 34 08 pm

**Comment by jwforres** [comment]
Do the horizontal lines going all the way across look strange when none of the donuts are there?

**Comment by spadgett** [comment]
> Do the horizontal lines going all the way across look strange when none of the donuts are there?

I only include them when there's at least one donut. And the sparklines are 100% width when there are no donuts.

screen shot 2016-12-05 at 2 43 10 pm

**Comment by spadgett** [comment]
If we always want the lines, this is how it looks:

screen shot 2016-12-05 at 2 45 47 pm

**Comment by jwforres** [comment]
im ok with either of those, though i think i prefer with the lines

**Comment by spadgett** [comment]
> i think i prefer with the lines

Let me add them to deployment metrics in that case to be consistent

**Comment by spadgett** [comment]
Added "Used" inside the donut.

screen shot 2016-12-05 at 3 04 32 pm

**Comment by spadgett** [comment]
Updated, @jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
