### PR TITLE
Use kebab menu for project list actions

### PR DESCRIPTION
**Pull request by spadgett**
See https://github.com/openshift/origin-web-console/issues/1485#issuecomment-297993588

openshift web console 2017-05-05 09-08-32

openshift web console 2017-05-05 09-09-44

### CODE REVIEW

**Comment by spadgett** [comment]
Fixed dist conflict

**Comment by jwforres** [comment]
@spadgett this is likely to affect QE automation, may want to let them know

**Comment by jwforres** [comment]
actually i think this will break our integration tests as well

**Comment by spadgett** [comment]
> actually i think this will break our integration tests as well

Yeah, I think so. Will fix

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
@jwforres Updated, PTAL

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
