### PR TITLE
Add headings to kve for env vars

### LINKED ISSUE #228: Environment variable editor should have column headings
While in a BuildConfig Environment edition, I've found the new editor confusing as there's no names for the columns (may seem obvious they are key and value) but it's not.

image

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix #228 

Adds the `show-header` attrib to the `kve` on:
- buildConfig
- build
- deploymentConfig
- deployment
- replicationController

screen shot 2016-08-19 at 11 35 39 am

**More needed?**
Trying to decide if it is necessary to add the headings everywhere.  For example, labels in the create from template flow:

screen shot 2016-08-19 at 11 48 30 am

And in create from image:
screen shot 2016-08-19 at 11 50 53 am

Seems clear enough in these instances.

@jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
no i agree with your assessment on those other ones

[merge]

**Comment by jwforres** [comment]
@benjaminapetersen dist problem

**Comment by benjaminapetersen** [comment]
pushed, [test]

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
rebased & [test] again?

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
woohoo

**Pull request merged**
