### PR TITLE
Create reusable edit-environment-variables component

### LINKED ISSUE #1651: Enter key doesn't save changes on Environment tab
The enter key does not submit the form when editing environment variables for a deployment config.

cc @benjaminapetersen

### PR DESCRIPTION
**Pull request by spadgett**
- Add environment variable support to stateful sets
- Remove duplicate code from controllers
- Fix problem where the enter key did not submit the environment form (closes #1651)
- Fix editor flicker on save

This would replace #1815 and #1803 

cc @jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
may want to let QE know to regression test the env editors since its a lot of changes

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Rebased to fix merge conflict (which is why it failed).

[merge]

**Comment by spadgett** [comment]
@jwforres created a card for QE: https://trello.com/c/3GxVdfi4

**Pull request merged**
