### PR TITLE
Truncate long event messages to 1000 characters

### LINKED ISSUE #54: Need to truncate long event messages
Usually event messages are a sentence or two, but it's possible for them to be very long. We should handle this better. For example,

openshift_web_console

/cc @jwforres

### PR DESCRIPTION
**Pull request by spadgett**
Occasionally an event can have a long message. Limit the length to 1000 characters or 4 lines in the events table.

Fixes #54

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres I added optional keyword highlighting to the `truncate-long-text` directive so that we can have both expand and keyword highlighting.

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
Hold, I found a minor issue with JSON formatting :/

**Comment by spadgett** [comment]
@jwforres Moved the `truncated-content` class to the correct `<span>`. No other changes.

[merge]

**Pull request merged**
