### PR TITLE
Don't wrap "Clear Filter" text

### PR DESCRIPTION
**Pull request by spadgett**
Before:

iphone x - ios 11 0 2017-11-02 13-04-13

After:

iphone x - ios 11 0 2017-11-02 13-08-36

@jwforres @rhamilto

### CODE REVIEW

**Comment by jwforres** [comment]
something is wrong with the line height, those two lines of text are too close together

**Comment by spadgett** [comment]
> something is wrong with the line height, those two lines of text are too close together

This is using the normal `h2` style. Seems to be the `line-height: 1.1` rule on headers coming from Bootstrap.

**Comment by jwforres** [comment]
We adjust the bootstrap header sizes in our variables, maybe we screwed up the line heights

**Comment by rhamilto** [comment]
We have many instances of "Clear Filter" now (browse pages).  We should probably change them all?

**Comment by spadgett** [comment]
@jwforres another look since I added the class to other instances?

**Pull request merged**
