### PR TITLE
Resolving bug where class name changed and I didn't notice while reba…

### PR DESCRIPTION
**Pull request by rhamilto**
…sing

@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
[merge]

**Comment by rhamilto** [comment]
@spadgett, I didn't realize you'd already put the merge tag on this and I pushed, so it looks like this is stuck?

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
AWS capacity error. Let's try again.

[merge]

**Pull request merged**
