### PR TITLE
Hide image 'Layers' tab if no layers are present

### PR DESCRIPTION
**Pull request by stefwalter**
Instead of showing an empty confusing image 'Layers' tab, hide
it when no layers are present or no layer information is present.

Sadly figuring out the cause and displaying an on point message
is not currently possible. So lets just hide the tab. That tells
the story: "The information does not exist"

### CODE REVIEW

**Comment by stefwalter** [comment]
Sadly npm's registry has crapped out and I'm not yet able to test this. Will try again tomorrow.

```
npm http 200 https://github.com/gruntjs/node-http2#fix-return-value
npm ERR! not a package /data/tmp/npm-20933-2exHKfMD/1471445501955-0.6207390709314495/tmp.tgz
npm ERR! Error: ENOENT, open '/data/tmp/npm-20933-2exHKfMD/1471445501955-0.6207390709314495/package/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.6.4-201.fc23.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /data/src/origin-web-console
npm ERR! node -v v0.10.42
npm ERR! npm -v 1.3.6
npm ERR! path /data/tmp/npm-20933-2exHKfMD/1471445501955-0.6207390709314495/package/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /data/src/origin-web-console/npm-debug.log
npm ERR! not ok code 0
```

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Q ~ I think we have been leaning towards showing the tabs but having an empty state message over hiding tabs altogether (ex. terminals discussion).  Not entirely sure if thats relevant here but wanted to mention it for consistency sake.

**Comment by jwforres** [comment]
@benjaminapetersen yeah i'll tweak it in a follow up PR

**Pull request merged**
