### PR TITLE
[WIP] Fix jshint task config to notice nested directories

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes issue #2999

screen shot 2018-05-14 at 2 50 03 pm 1

We don't have a ton of problems at the moment, and won't so long as we don't do a lot of nested directories...

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
If no objections, I can put it on my list to scrub all the problems && remove the `[WIP]`.

**Comment by spadgett** [comment]
That would do it :/

How many errors?

**Comment by spadgett** [comment]
Let's go ahead and fix. We probably want to wait for 3.11 unless you find one that results in a user-visible bug. Thanks for catching this!

**Comment by benjaminapetersen** [comment]
Yeah, I agree, I don't think there is a rush, just glad to catch early enough to avoid too much drift...

**Pull request closed without merging**
