### PR TITLE
Updating PatternFly and Angular-PatternFly to v3.21.0

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by spadgett** [comment]
> +190,739 −18,476

Do we know what's adding so many lines?

**Comment by rhamilto** [comment]
@spadgett, it's [the new fonts](https://github.com/patternfly/patternfly/commit/c9800ee1a2876aa9accc351ea3618a9173357db0).  
Hold on this one sec as I forgot to remove the resolutions we added to get KVE to merge.

**Comment by jwforres** [comment]
You may not be able to remove them completely until we get a new devenv_ami
build.  You probably need to just update the resolution version numbers as
part of this PR for now.

**Comment by rhamilto** [comment]
Ok.  I bumped the resolution version numbers.  It should be ok now.

**Comment by rhamilto** [comment]
@spadgett, once this merges, can you rebase your overview-redesign branch again since this PR has the necessary list-pf CSS?

**Comment by spadgett** [comment]
Will do

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
