### PR TITLE
Issue 73 - Delete Confirmation Modal Auto-focus

### LINKED ISSUE #73: Input box in 'delete project' modal should get focus
When you are on the project settings page and choose "delete" from the drop down menu, a modal appears asking you to type the project name.  The input does not automatically receive focus.

### PR DESCRIPTION
**Pull request by MDeMariaRH**
Delete confirmation input now gets autofocus on display as stated in #73 

Fixes #73

### CODE REVIEW

**Comment by spadgett** [comment]
Missing `dist`.

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Thanks @MDeMariaRH

**Comment by benjaminapetersen** [comment]
+1

**Pull request merged**
