### PR TITLE
complete/correct README for Production builds

### PR DESCRIPTION
**Pull request by zhanghaohao**
origin-web-console repo use go-bindata tool to generate bindata.go from dist folder , but the README has not completed this part , give out approaches for different branches .
Also correct the rebuild images and binaries part according to different branches .

### CODE REVIEW

**Comment by zhanghaohao** [comment]
Fix https://github.com/openshift/origin-web-console/issues/2694

**Comment by spadgett** [comment]
I think it would be better to link to the instructions in https://github.com/openshift/origin-web-console-server so we only have them in one place. We should correct any errors if those instructions aren't accurate.

**Comment by zhanghaohao** [comment]
sure, i have changed REAMDE.md according to your comment

**Comment by zhanghaohao** [comment]
could we ignore the Travis CI build failed message ? because i successfully built on my mac

**Comment by zhanghaohao** [comment]
run "grunt build" , then commit due to Travic CI build failed 
now Travis CI build succeed

**Pull request closed without merging**
