### PR TITLE
Add select picker to env tab on pod page

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Looking @ addressing #620 

screen shot 2016-10-13 at 4 44 22 pm

@jwforres @spadgett

### CODE REVIEW

**Comment by jwforres** [comment]
Is the "Container hello-openshift Environment Variables" something being passed into the kve? Otherwise i think I'd rather see Container [container dropdown] environment variables

**Comment by spadgett** [comment]
It seems odd that the environment tab on the pod page would be different than deployment configs and replication controllers. But if we change the other pages, we'll have to think about editing environment variables. Not sure how well the dropdown works in those cases. If I add a variable and switch containers, will I lose my change? What if I have an invalid value in a field that's not visible?

This also doesn't fix any performance problems if there are a lot of variables for one container. I think we need to reproduce and profile the key value editor to find the bottleneck.

**Comment by benjaminapetersen** [comment]
@jwforres agree, lemme check and get rid of that extra heading.
@spadgett yeah, I dont think this fixes all performance probs by any means, but I do think its more consistent w/other tabs where we use the drop down for containers.  Its at least easier to digest.  Def need to figure out the performance bottleneck issue as well.

**Comment by spadgett** [comment]
>  but I do think its more consistent w/other tabs where we use the drop down for containers

Right, but it's an editor, too. So we need to solve the usability problems with using selects for editing. And we should look at updating the "Set Resource Limits" and "Add Health Checks" editors if we add the container select here.

**Comment by benjaminapetersen** [comment]
Ie, decide if we want a "done" button for each one & alert the user if they select a different container but haven't finished the first?  We could let them edit both & submit, but I wonder if that is a more confusing interface.

**Comment by spadgett** [comment]
> decide if we want a "done" button for each one

The problem is the first done click will usually trigger a new deployment for a deployment config. Then you'll get a bunch of conflict errors if you try to edit the second container's variables because of deployment status updates.

**Comment by benjaminapetersen** [comment]
Hmm. So perhaps a msg indicating "currently editing, not saved", might even be smart to put the "done" button on top...?

**Comment by benjaminapetersen** [comment]
Looking at this again. Ideally we would disable  the `save` on submit and enable when things have settled, but it isn't clear to me that we can really know if its truly settled.  

I'm looking at DCs now.  When I change an env var, I'll get ~10 updates via `DataService.watchObject("deploymentconfigs"...)`.

**Pull request closed without merging**
