### PR TITLE
Bump openshift-jvm to 1.0.46

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett  PTAL

FYI @gashcrumb @astefanutti @jimmidyson

**Comment by spadgett** [comment]
LGTM. Verified the console and icons load in the built openshift binary.

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
> Verifying that checked in built files under dist match the source...
> Built dist does not match what is committed, run 'grunt build' and include the results in your commit.

**Comment by jwforres** [comment]
but travis passed, so travis saw a clean dist diff
trying one more time while i do a clean install of deps
[merge]

**Comment by jwforres** [comment]
fixed Gruntfile to delete dist.java during build process, trying again [merge]

**Comment by spadgett** [comment]
@jwforres merging #484 with your commit

**Comment by spadgett** [comment]
Closing since #484 has merged.

**Pull request closed without merging**
