### PR TITLE
Updates to integration testing to support tests in a docker container

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
[test]

**Comment by jwforres** [comment]
@spadgett PTAL i'm letting the test browser be specified by a flag and defaulting to chrome for now, we can flip to firefox by default once its available in the AMIs if we want to be consistent with what the release tests are run in

**Comment by spadgett** [comment]
LGTM

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
