### PR TITLE
Bump origin-web-catalog to 0.0.7

### PR DESCRIPTION
**Pull request by spadgett**
Contains the markup changes we'll need when we next bump origin-web-catalog due to https://github.com/openshift/origin-web-catalog/pull/127

### CODE REVIEW

**Comment by spadgett** [comment]
Depends on https://github.com/openshift/origin-web-catalog/pull/130

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
@spadgett were you ready to merge this?

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
