### PR TITLE
Update template annotations

### PR DESCRIPTION
**Pull request by spadgett**
- template.openshift.io/provider-display-name -> openshift.io/provider-display-Name
- template.openshift.io/documentation-url -> openshift.io/documentation-url
- template.openshift.io/support-url -> openshift.io/support-url

See also https://github.com/openshift/origin-web-catalog/pull/487

### CODE REVIEW

**Comment by spadgett** [comment]
@sspeiche @bparees FYI

**Comment by bparees** [comment]
you'll want to wait until https://github.com/openshift/origin/pull/16925 merges for this to go in, i think.

**Comment by spadgett** [comment]
Upstream PR merged

/hold cancel
/assign @jwforres

**Pull request merged**
