### PR TITLE
Bump layout.attrs version to latest to pickup mobile size fix.

### PR DESCRIPTION
**Pull request by sg00dwin**
@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
looks like the update dropped a bunch of webkit specific css, is that expected?

**Comment by sg00dwin** [comment]
Actually those came out in @rhamilto pr https://github.com/benjaminapetersen/layout.attrs/pull/17
so I'm assuming they were no longer needed? that correct @rhamilto ?

**Comment by rhamilto** [comment]
Yep, that's correct.  [Autoprefixer dropped those](https://github.com/postcss/autoprefixer#only-actual-prefixes).

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
