### PR TITLE
[Bug 1608289] Expand button should be enabled as long as the size don…

### PR DESCRIPTION
**Pull request by cloudbehl**
…'t exceed limit

We don't need to check if we are out of claims or not if we are expanding the PVC because the PVC is already created.

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by spadgett** [comment]
Thanks @cloudbehl. Needs dist files

**Comment by cloudbehl** [comment]
@spadgett aah, sorry! Added dist files now.

**Comment by spadgett** [comment]
@cloudbehl thanks, i think you'll need to run `bower install` and `grunt build` again as well

**Comment by cloudbehl** [comment]
@spadgett is it good now? Let me know anything else is required.

**Pull request merged**
