### PR TITLE
Change how service grouping border is created

### PR DESCRIPTION
**Pull request by sg00dwin**
- position it in front of deployment tiles
	- use patternfly blue

@jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
@sg00dwin We picked the blue to match the other items on the page (navbar highlights and donuts). Do you have a screenshot of what it looks like now?

**Comment by sg00dwin** [comment]
It's slightly darker than previous color. I noticed it was what patternfly uses for tiles, but can switch it back.

screen

**Comment by spadgett** [comment]
Can't decide. It doesn't look bad, but is it weird that we have a similar left border in the left nav that is a different color? @jwforres @rhamilto ?

**Comment by jwforres** [comment]
I actually kind of like it, if it weren't for that left bar in the nav :-\

maybe we should get SJ to take a look at it

**Comment by sg00dwin** [comment]
@spadgett, @jwforres I reverted to the original blue, so that I can get the primary fix in. Placing the blue bar above the deployment block left edges.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
