### PR TITLE
Include origin-web-catalogs library.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
This PR pulls in the origin-web-catalogs dependency. None of the catalog components are used yet but this gives the ability to start doing so.

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
@jwforres @spadgett

**Comment by jeff-phillips-18** [comment]
Please let me know when you think we are at a point to consider this and we can rev origin-web-catalog and I will update this PR to use the new version.

**Comment by jwforres** [comment]
@jeff-phillips-18 lets go ahead and do it, I think we will probably just need to rev catalog and update console several times over the next couple of weeks.

**Comment by jeff-phillips-18** [comment]
This PR now includes v0.0.3 of origin-web-catalog

**Comment by jeff-phillips-18** [comment]
Modified code to prevent overwriting OPENSHIFT_CONSTANTS settings that may already be set.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
