### PR TITLE
Aligning kebab styles with PatternFly

### LINKED ISSUE #1262: Dropdown kebab styling not consistent with PatternFly
Existing kebabs:

screen shot 2017-02-17 at 11 36 03 am

PatternFly:

screen shot 2017-02-17 at 11 37 03 am

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1262 

Before:

screen shot 2017-02-17 at 3 31 03 pm
screen shot 2017-02-17 at 3 31 11 pm

After:

screen shot 2017-02-17 at 3 29 33 pm
screen shot 2017-02-17 at 3 29 42 pm

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by rhamilto** [comment]
[test]

**Comment by rhamilto** [comment]
@spadgett, we'll want this one in your rebase of overview-redesign, too.  I'll need to rebase it once #1284 lands.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
