### PR TITLE
Fix binding display in collapsed service instance rows

### PR DESCRIPTION
**Pull request by spadgett**
cc @benjaminapetersen

### CODE REVIEW

**Comment by jwforres** [comment]
Change LGTM but Travis isn't happy

**Comment by spadgett** [comment]
Diff in vendor.js. I suspect a dependency changed

**Comment by spadgett** [comment]
Travis is happy now

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
Looks like a flake

> Running "copy:extensions" (copy) task
> Warning: Unable to create directory "/data/src/github.com/openshift/origin-web-console/.tmp" (Error code: EEXIST). Use --force to continue.
> Aborted due to warnings.

[merge]

**Comment by spadgett** [comment]
> Error: Timed out waiting for the WebDriver server at http://172.18.9.138:44850/wd/hub

[merge]

**Comment by benjaminapetersen** [comment]
+1 thanks @spadgett, I included that in the PR I just opened, but def better to get it sooner!

**Pull request merged**
