### PR TITLE
Improve Jenkinsfile examples

### LINKED ISSUE #952: Provide Jenkinsfile example of running unit tests in a slave
As a follow-on to:

https://github.com/openshift/origin-web-console/pull/947

It would be helpful to provide an example of running unit tests in a jenkins slave.  Generally the unit tests have to run in a slave because the required libraries won't be available on jenkins itself.  @csrwng Is currently working on some examples we should be able to pull from.

### PR DESCRIPTION
**Pull request by spadgett**
Show more complete examples, including running commands on labelled nodes.

@csrwng Do these examples look correct / realisitc?

screen shot 2017-01-03 at 12 41 42 pm

Fixes #952

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres This makes the dialog larger, but it scrolls OK on smaller screens.

**Comment by jwforres** [comment]
I'd be tempted to combine the first and last ones, and just make the build/deploy the first example. That would shorten it up a bit, four large example blocks feels a little overwhelming

**Comment by spadgett** [comment]
@jwforres better?

screen shot 2017-01-03 at 12 59 05 pm

**Comment by jwforres** [comment]
yeah that seems better to me

**Comment by csrwng** [comment]
The examples look good to me

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
