### PR TITLE
Allow unlinking a service with no deployments

### LINKED ISSUE #450: On the overview, it is not possible to ungroup a service that has no deployments
To recreate:

1.  Add jenkins-pipeline-example to a new project and wait for deployments of database, jenkins, and jenkins-jnlp to appear
1.  Click the link icon in the jenkins service title bar
1.  Choose "frontend" from the dropdown
1.  Click "OK"
1.  Note that a new "No Deployments." box has been added to jenkins, but there is no remove icon to undo your action

screen shot 2016-08-22 at 3 45 12 pm

### PR DESCRIPTION
**Pull request by spadgett**
Fixes #450 

Edit: removed out of date screenshot

@jwforres @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
Let me know how you feel about this. I was thinking this is the lower risk change for 1.3.

**Comment by jwforres** [comment]
can we not use the same icon indicator in the top right of the block?

**Comment by spadgett** [comment]
I have the header working without too many changes.

openshift_web_console

**Comment by spadgett** [comment]
It does make it more obvious when there's no service vs a service with no deployments:

openshift_web_console

**Comment by spadgett** [comment]
@jwforres I toned down the drop shadow when there are no deployments.

screen shot 2016-08-23 at 9 02 08 am

**Comment by jwforres** [comment]
LGTM

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
