### PR TITLE
Add nav and simple body content into the ng-view node so we have content until api discovery finishes

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/8638

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
thanks [merge]

**Comment by spadgett** [comment]
```
Verifying that checked in built files under dist match the source...
Built dist does not match what is committed, run 'grunt build' and include the results in your commit.
Error while running ssh/sudo command: 
set -e
pushd /data/src/github.com/openshift//origin-web-console >/dev/null
export PATH=$GOPATH/bin:$PATH
```

**Comment by jwforres** [comment]
Ah right, do still need a dist for index.html

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
@stevekuznetsov bot's got a bug, i pushed a new commit after the failure and tagged it for merge again but the bot's not recognizing there is a new commit

```
****Processing MERGE in 'master' branch for user 'jwforres' on: https://github.com/openshift/origin-web-console/pull/295
  Updated at: 2016-08-04 20:58:53 UTC
  Changed after evaluated time: true
  Trigger updated at: 2016-08-04 20:59:03 UTC
  Evaluated time: 2016-08-04 20:17:09 UTC
  Job failed: Origin Web Console Merge Results: FAILURE (https://ci.openshift.redhat.com/jenkins/job/test_pull_requests_origin_web_console/209/)
  No flake identification configuration exists, resubmitting...
```

**Comment by stevekuznetsov** [comment]
@jwforres I screwed up an update and the bot regressed to pick that bug back up ... my apologies. I'll fix tomorrow morning, no access to Jenkins from home

**Comment by stevekuznetsov** [comment]
Manual trigger didn't work...
```
+ test_pull_requests --merge_pull_request 295 --repo origin-web-console --config /var/lib/jenkins/.test_pull_requests_origin_console.json
  Merging pull request #295 for repo 'origin-web-console'
  Test merging pull request #295 for repo 'origin-web-console'
  Evaluated time: 2016-08-04 20:17:09 UTC
  Updated at: 2016-08-04 20:58:53 UTC
/bin/test_pull_requests:602:in `test_merge_pull_request': Pull request was updated after testing started! (RuntimeError)
	from /bin/test_pull_requests:525:in `merge_pull_request'
	from /bin/test_pull_requests:1875:in `<main>'
Build step 'Execute shell' marked build as failure
```

**Comment by jwforres** [comment]
If you think its the same bug as yesterday I can just delete the bot
comments and get it to trigger again, was just leaving it in this state in
case you needed to debug

**Comment by stevekuznetsov** [comment]
@jwforres up to you -- if you need this in before tomorrow morning, go ahead and make that happen, if not, having some time to debug would be nice

**Comment by jwforres** [comment]
No rush, I will leave it

**Pull request merged**
