### PR TITLE
Adopt service catalog API changes

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/y1lbFrbp

Bumps origin-web-common 0.0.63 -> 0.0.64
Bumps origin-web-catalog 0.0.52 -> 0.0.53

Requires https://github.com/openshift/origin-web-catalog/pull/448
Requires https://github.com/openshift/origin-web-common/pull/199

@jeff-phillips-18 FYI

### CODE REVIEW

**Comment by spadgett** [comment]
@jeff-phillips-18 PTAL

**Comment by jeff-phillips-18** [comment]
I think we need to go thru the rest of the code and replace creators of the resource objects that are not using the APIService.getPreferredVersion to get the resource. Places like:
https://github.com/spadgett/origin-web-console/blob/plans-resource/app/scripts/directives/resourceServiceBindings.js#L86-L89

will break when we get the service catalog changes.

**Comment by spadgett** [comment]
Yeah it's a good idea. I can take a swing at it.

**Comment by spadgett** [comment]
@jeff-phillips-18 Thanks, updated.

I'm considering making some changes to not always pull all service plans in these PRs, but that could also be a follow on. It's potentially a lot of data.

**Comment by jeff-phillips-18** [comment]
Also, there is a Catalog service (in origin-web-catalog) that retrieves the service plans so a lot of this could be replaced with Catalog.getServicePlans. Maybe add some other utilities to getServicePlansForServiceClass and getServicePlanByName.

**Comment by spadgett** [comment]
Rebased and updated for #2215

**Comment by spadgett** [comment]
Squashed and rebased

**Comment by spadgett** [comment]
Origin changes: https://github.com/openshift/origin/pull/16689

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
@jeff-phillips-18 OK to merge? The upstream changes have merged.

**Comment by spadgett** [comment]
Thanks @jeff-phillips-18 

[merge]

**Comment by spadgett** [comment]
Rebased

**Pull request merged**
