### PR TITLE
[enterprise-3.9] Bug 1607150 - UI Timeout causing IE 11 to automatically log out

### PR DESCRIPTION
**Pull request by jhadvig**
manually backporting https://github.com/openshift/origin-web-console/pull/3041

@spadgett fyi

### CODE REVIEW

**Comment by spadgett** [comment]
/hold
because the tests are skipped

**Comment by jhadvig** [comment]
@spadgett the 3.10 cherrypick got merged without any issues. I see that the jenkins tests are skipped. Not sure what to do at this point.

**Comment by spadgett** [comment]
@jhadvig Yeah, we need https://github.com/openshift/release/pull/1137 to merge to run tests. I'll rebase this morning and work with @stevekuznetsov to get that in.

**Pull request merged**
