### PR TITLE
Add additional add to project options to overview empty state

### LINKED ISSUE #2631: Project overview empty state Add to Project button links to catalog page, but other add options not visible on the catalog page
screen shot 2018-01-05 at 10 21 46 am

The result of clicking "Add to Project" in the previous screenshot brings you here, and the page has no mention of the other add methods:
screen shot 2018-01-05 at 10 23 21 am

The old create page had tabs at the top with the other add methods:
screen shot 2018-01-05 at 10 24 49 am

And the landing page has the other add options listed:
screen shot 2018-01-05 at 10 25 25 am

It seems like we should be consistent?

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #2631

localhost_9000_dev-console_project_myproject_overview ipad pro
localhost_9000_dev-console_project_myproject_overview iphone 6 1

### CODE REVIEW

**Comment by rhamilto** [comment]
@openshift/team-ux-review, there are some reservations regarding the three secondary action buttons, so I wanted to make sure y'all see the screenshots above.

**Comment by jwforres** [comment]
This doesn't lay out well when the buttons have realistic content in them, i.e. actions of different string lengths.

**Comment by beanh66** [comment]
@rhamilto I would suggest making all buttons on the empty state pattern the same width.  Can we make that change here and contribute back to PF? Trying to figure out the best way to implement. I am happy to update the design documentation on PF as well. I agree it could look better so thanks for bringing it up with these screenshots. Independently, should we stack all 4 buttons on mobile? IMO, we should. Something like this: 
screen shot 2018-01-10 at 12 31 15 pm

**Comment by serenamarie125** [comment]
I agree @beanh66 .  Would be best to have this in PF first, but unsure priority of fix.  I like vertically stacking the buttons, and fits well with the current PF Empty state pattern.

**Comment by jennyhaines** [comment]
@beanh66 - I think that vertically stacking the buttons would help the mobile layout, too. I like this solution for both desktop and mobile.

**Comment by rhamilto** [comment]
I'm not sure fixing the width of the buttons is a tenable solution.  Making the buttons the same width in PatternFly is problematic since we have no idea what the labels will be; how do you decide what the right width is?  And in OpenShift, we will one day likely need to internationalize, and it seems likely that label length will vary across languages.

So spitballing another idea... what if we use a [button group](https://getbootstrap.com/docs/3.3/components/#btn-groups) for the secondary actions at resolutions greater that 479px, and stack the secondary actions vertically at mobile less than 480px?

screen shot 2018-01-10 at 1 41 50 pm

screen shot 2018-01-10 at 1 56 45 pm

**Comment by spadgett** [comment]
Can we use flexbox to make the buttons the same width without needing a fixed size?

**Comment by rhamilto** [comment]
> Can we use flexbox to make the buttons the same width without needing a fixed size?

That's a possibility at resolutions greater than 479px.  I'm not sure the resulting appearance is desirable, however.  To my eye, the secondary action buttons become dominant.
screen shot 2018-01-10 at 2 14 07 pm

**Comment by rhamilto** [comment]
And I made the secondary actions size small in the screenshot above.

**Comment by rhamilto** [comment]
Sorry, @spadgett.  I inadvertently deleted your comment:

> Can we use flexbox to make the buttons the same width without needing a fixed size?

**Comment by ncameronbritt** [comment]
@rhamilto Is there some kind of flexbox trickery you could do for the primary action button that would increase the padding like the secondary actions? So that all four buttons seem more related... Just curious what that might look like.

**Comment by rhamilto** [comment]
> @rhamilto Is there some kind of flexbox trickery you could do for the primary action button that would increase the padding like the secondary actions? So that all four buttons seem more related... Just curious what that might look like.

screen shot 2018-01-10 at 2 38 10 pm

**Comment by rhamilto** [comment]
Sorry.  In those last two screenshots, "Deploy Image" was a btn-sm, but the other two were not.  Fixed it so they're all btn-sm.

screen shot 2018-01-10 at 2 42 34 pm

**Comment by cshinn** [comment]
@rhamilto that looks pretty good! Does it hold up in on large window sizes?

**Comment by beanh66** [comment]
Agreed, looks great @rhamilto

**Comment by rhamilto** [comment]
> Does it hold up in on large window sizes?

Yeah.  It never gets larger than it appears in https://github.com/openshift/origin-web-console/pull/2644#issuecomment-356714686 due to a max-width set on the empty-state-message.

This might be a good compromise:
http://recordit.co/TvaV5b6HCM

Because the labels vary in length, I can't keep the buttons the exact same size at the smallest viewport resolution of 320px, but I can let them grow to equal size as the viewport gets bigger.

**Comment by jennyhaines** [comment]
@rhamilto - I think that button size transition between viewport widths looks good!

**Comment by rhamilto** [comment]
PR updated with changes recorded in http://recordit.co/TvaV5b6HCM.

**Comment by ncameronbritt** [comment]
Flexbox ftw

**Comment by beanh66** [comment]
@rhamilto Looks like a great solution. Is it possible to contribute this code back to PatternFly so other products can use the Empty State in a similar way? Thoughts @dtaylor113?

**Comment by rhamilto** [comment]
>  Is it possible to contribute this code back to PatternFly so other products can use the Empty State in a similar way?

I can, but understand this fix is specific to **three** secondary action buttons.  I think the PatternFly solution needs to be more robust in its approach to a variable number of buttons, and I'm not sure how to go about doing that.  It seems like this should become an upstream issue to be solved by the community at large given the complexity of the problem and the issues with the existing empty state solution in PatternFly.

**Pull request merged**
