### PR TITLE
Fix problem where UI appears unresponsive while waiting for websocket update

### LINKED ISSUE #1875: Resume rollouts link appears to do nothing if watch updates are slow or websocket is disconnected
The resume rollouts action on the overview and browse pages doesn't disappear on click until after we get a watch update saying that `spec.paused` is set to false. This means the link appears to do nothing if the websocket update doesn't happen immediately.

@smarterclayton Resume rollouts is working for me in current master for both deployments and deployment configs, so I suspect it is in fact slow watches.

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix #1875 
@spadgett 

(aside, i think the dist having something to the effect of `return !0` for `return true` is kinda funny... optimize out those 2 characters 😄 )

### CODE REVIEW

**Comment by spadgett** [comment]
We also have the issue on the deployment config and deployment pages

**Comment by benjaminapetersen** [comment]
Looking at these.

**Comment by benjaminapetersen** [comment]
Updated.
Interested in reducing the code duplication & reusing `alerts` here, but prob not in scope for a bug fix.  Something like:

```html
  <alerts 
    ng-if="deployment.spec.paused && !updatingPausedState"
    alerts="pausedAlert"></alerts>
```

**Comment by benjaminapetersen** [comment]
This can go today as well, if we can wake up the merge queue...

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
