### PR TITLE
Bug 1334630 - update Template's objects, params and labels

### PR DESCRIPTION
**Pull request by jhadvig**
@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
👍  [merge]

**Comment by spadgett** [comment]
@jwforres have you seen this before?

```
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
The last active task was: 
unknown
```

**Comment by spadgett** [comment]
https://ci.openshift.redhat.com/jenkins/job/merge_pull_requests_origin_web_console/10/console

**Comment by spadgett** [comment]
[merge]

**Comment by jwforres** [comment]
if 11 of 11 spec tests failed my first guess was that the api server failed
to start for some reason, its what i was getting during my testing of the
new vagrant steps when i realized the server wasnt started automatically.
I'm planning on getting a dump from journalctl for the openshift service as
one of the download artifacts so that we can diagnose those issues if they
pop up

**Pull request merged**
