### PR TITLE
Adjust notification drawer events to show

### PR DESCRIPTION
**Pull request by spadgett**
- Show events when pods fail to schedule
- Show an event for invalid environment variable names
- Remove ErrorAsyncOperationInProgress and ReferencesNonexistentInstance because they are expected and generate a lot of noise with in-context bind.

### CODE REVIEW

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by spadgett** [comment]
Looks like flake #1684

[merge][severity: bug]

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by spadgett** [comment]
Opened test flake #2037. It looks like it might be different than flake #2016

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by spadgett** [comment]
[test]

**Comment by benjaminapetersen** [comment]
```bash 
[launcher] Process exited with error code 1
>> A Jasmine spec timed out. Resetting the WebDriver Control Flow.
>> The last active task was: 
>> unknown
>> A Jasmine spec timed out. Resetting the WebDriver Control Flow.
>> The last active task was: 
>> unknown
>> A Jasmine spec timed out. Resetting the WebDriver Control Flow.
>> The last active task was: 
>> unknown
Fatal error: protractor exited with code: 1
```

Re origin [issue 16279](https://github.com/openshift/origin/issues/16279)

**Comment by spadgett** [comment]
[test]

**Pull request merged**
