### PR TITLE
Removing old overview code

### LINKED ISSUE #220: Remove previous overview code
Tech debt issue to track removing the old overview code.

/cc @jwforres @rhamilto

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #220

### CODE REVIEW

**Comment by rhamilto** [comment]
[test]

**Comment by spadgett** [comment]
Should be able to remove `.empty-project` from core.less (line 122)

**Comment by spadgett** [comment]
I believe there are some styles in _component-animations.less we can remove.

**Comment by spadgett** [comment]
Should be able to remove `.triggers .build` from

https://github.com/spadgett/origin-web-console/blob/e80630f386de5dda387c500f14f7f18e03a8ff19/app/styles/_pipeline.less#L510

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
