### PR TITLE
Achieve equal height deployment tiles and enable option to append...

### PR DESCRIPTION
**Pull request by sg00dwin**
multiple tile blocks if needed

@jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
Can you check safari with 2 or more dependent services? Worried about flex basis 0%

**Comment by sg00dwin** [comment]
@spadgett updated so overview-service and no-deployments block use flex-basis: 49% which displays good cross browsers. Safari, FF, Chrome, IE

group

**Comment by sg00dwin** [comment]
@jwforres updated pr correct no deployments block.

updated

**Comment by jwforres** [comment]
issues with standalone services

edge-cases

**Pull request closed without merging**
