### PR TITLE
Bug 1333162 Improve descriptions for quota scopes

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1333162

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
cc @derekwaynecarr 

We originally used the same wording as the CLI. Do we want to update the CLI as well?

**Comment by jwforres** [comment]
some of these are specific to openshift, like the one that references builds, so if did update the CLI we would probably need to have different text in kubectl vs oc, or just change the text in oc

**Comment by jwforres** [comment]
cc @fabianofranz @juanvallejo for the CLI discussion

**Comment by juanvallejo** [comment]
I think these two updates would be fine for both openshift and kubernetes
```
"BestEffort": "Affects pods that do not have resource limits set. These pods have a best effort quality of service.",
"NotBestEffort": "Affects pods that have at least one resource limit set. These pods do not have a best effort quality of service."
```

Not sure if the concept of "applications" exists upstream, if this is the case, maybe we could list more detail on what consists of an application?
```
"NotTerminating": "Affects pods that do not have an active deadline. These pods usually include your applications.",
```

@fabianofranz WDYT?

**Comment by jwforres** [comment]
I don't think the strings necessarily need to match 100% between the CLI and the console, but @juanvallejo can you open an issue for the CLI in origin to consider changing the CLI strings.

@spadgett can we merge this?

**Comment by spadgett** [comment]
[merge]

**Comment by juanvallejo** [comment]
@jwforres 
> I don't think the strings necessarily need to match 100% between the CLI and the console, but @juanvallejo can you open an issue for the CLI in origin to consider changing the CLI strings.

Sounds good, opened issue here https://github.com/openshift/origin/issues/11985

**Comment by jwforres** [comment]
had to abort previous job, it was stuck [merge]

**Pull request merged**
