### PR TITLE
Update buildConfig getPreferredVersion for instantiate

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Depends on [web-common PR 201](https://github.com/openshift/origin-web-common/pull/201) and [web-common PR 202](https://github.com/openshift/origin-web-common/pull/202)

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Rebased/retested, this one should be good to go.
@spadgett

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
