### PR TITLE
Allow special characters in search keywords

### PR DESCRIPTION
**Pull request by spadgett**
Correctly filter and highlight special characters in text filters like
the project list and catalog. Fix an issue where project names with
special characters didn't display correctly in the create from URL page
select.

@rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres please take a look at the JS. @rhamilto is going to tweak the `mark` style for use with `ui-select`

**Comment by jwforres** [comment]
JS LGTM

**Comment by spadgett** [comment]
@jwforres please take a look at the last commit

**Comment by jwforres** [comment]
LGTM

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
