### PR TITLE
Bug 1688318 -Added check before calculating min and max limit

### LINKED ISSUE #3096: 3.11 web console fail to expand PVC if resourcequota defined in project
OKD 3.11 (enabled ExpandPersistentVolumes), with Netapp Trident NAS storageclass (v18.10) (enabled allowVolumeExpansion)

I can enlarge PVC via both web console or oc cli if the project does not have resourcequota.
If project has a "hard" resourcequota on "requests.storage", I can only enlarge the PVC via oc cli. Web console fails and show "Can't be greater than ."

CentOS Linux release 7.5.1804 (Core)
ansible 2.6.5
openshift-ansible-3.11.37-1.git.0.3b8b341.el7.noarch

### PR DESCRIPTION
**Pull request by cloudbehl**
Fixes #3096
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1688318

### CODE REVIEW

**Comment by spadgett** [comment]
Thanks! Please rebase on branch enterprise-3.11

**Comment by cloudbehl** [comment]
@spadgett Thanks, Rebased the PR!

**Comment by spadgett** [comment]
thanks. lgtm, but you'll need to include the dist files

**Comment by cloudbehl** [comment]
> thanks. lgtm, but you'll need to include the dist files

Ohh I forgot, we used to do that over here.

But when I am doing `grunt build` I am able to see too much of files getting deleted and modified. Is there something that I am missing?

output after grunt build:
```
[anbehl@dhcp35-82 origin-web-console]$ git status
On branch ankush
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   app/index.html
	deleted:    dist.java/java/404.html
	deleted:    dist.java/java/app-747a60cd4f.js
	deleted:    dist.java/java/favicon.ico
	deleted:    dist.java/java/fonts/DroidSansMono-webfont.eot
	deleted:    dist.java/java/fonts/DroidSansMono-webfont.svg
	deleted:    dist.java/java/fonts/DroidSansMono-webfont.ttf
	deleted:    dist.java/java/fonts/DroidSansMono-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-Bold-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-Bold-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-Bold-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-Bold-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-BoldItalic-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-BoldItalic-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-BoldItalic-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-BoldItalic-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-ExtraBold-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-ExtraBold-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-ExtraBold-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-ExtraBold-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-ExtraBoldItalic-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-ExtraBoldItalic-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-ExtraBoldItalic-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-ExtraBoldItalic-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-Italic-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-Italic-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-Italic-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-Italic-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-Light-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-Light-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-Light-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-Light-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-LightItalic-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-LightItalic-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-LightItalic-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-LightItalic-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-Regular-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-Regular-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-Regular-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-Regular-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-Semibold-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-Semibold-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-Semibold-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-Semibold-webfont.woff
	deleted:    dist.java/java/fonts/OpenSans-SemiboldItalic-webfont.eot
	deleted:    dist.java/java/fonts/OpenSans-SemiboldItalic-webfont.svg
	deleted:    dist.java/java/fonts/OpenSans-SemiboldItalic-webfont.ttf
	deleted:    dist.java/java/fonts/OpenSans-SemiboldItalic-webfont.woff
	deleted:    dist.java/java/fonts/PatternFlyIcons-webfont.eot
	deleted:    dist.java/java/fonts/PatternFlyIcons-webfont.svg
	deleted:    dist.java/java/fonts/PatternFlyIcons-webfont.ttf
	deleted:    dist.java/java/fonts/PatternFlyIcons-webfont.woff
	deleted:    dist.java/java/fonts/fontawesome-webfont.eot
	deleted:    dist.java/java/fonts/fontawesome-webfont.svg
	deleted:    dist.java/java/fonts/fontawesome-webfont.ttf
	deleted:    dist.java/java/fonts/fontawesome-webfont.woff
	deleted:    dist.java/java/fonts/fontawesome-webfont.woff2
	deleted:    dist.java/java/fonts/glyphicons-halflings-regular.eot
	deleted:    dist.java/java/fonts/glyphicons-halflings-regular.svg
	deleted:    dist.java/java/fonts/glyphicons-halflings-regular.ttf
	deleted:    dist.java/java/fonts/glyphicons-halflings-regular.woff
	deleted:    dist.java/java/fonts/glyphicons-halflings-regular.woff2
	deleted:    dist.java/java/img/OpenShift-Logo-NoText.svg
	deleted:    dist.java/java/img/OpenShift-Logo-Text.svg
	deleted:    dist.java/java/img/OpenShift-logo.svg
	deleted:    dist.java/java/img/RH_Atomic-Logo-NoText.svg
	deleted:    dist.java/java/img/RH_Atomic-Logo-Text.svg
	deleted:    dist.java/java/img/RH_atomic.svg
	deleted:    dist.java/java/img/ZeroClipboard.swf
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-114.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-144.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-152.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-180.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-57.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-72.png
	deleted:    dist.java/java/img/apple-touch-icon-precomposed-76.png
	deleted:    dist.java/java/img/bg-login.jpg
	deleted:    dist.java/java/img/bg-modal-about-pf.png
	deleted:    dist.java/java/img/bg-navbar-pf-alt.svg
	deleted:    dist.java/java/img/brand-alt.svg
	deleted:    dist.java/java/img/brand.svg
	deleted:    dist.java/java/img/favicon.ico
	deleted:    dist.java/java/img/hawtio_logo.svg
	deleted:    dist.java/java/img/icons.gif
	deleted:    dist.java/java/img/icons/activemq/connector.png
	deleted:    dist.java/java/img/icons/activemq/listener.gif
	deleted:    dist.java/java/img/icons/activemq/message_broker.png
	deleted:    dist.java/java/img/icons/activemq/queue.png
	deleted:    dist.java/java/img/icons/activemq/queue_folder.png
	deleted:    dist.java/java/img/icons/activemq/sender.gif
	deleted:    dist.java/java/img/icons/activemq/topic.png
	deleted:    dist.java/java/img/icons/activemq/topic_folder.png
	deleted:    dist.java/java/img/icons/camel.svg
	deleted:    dist.java/java/img/icons/camel/aggregate24.png
	deleted:    dist.java/java/img/icons/camel/bean24.png
	deleted:    dist.java/java/img/icons/camel/breakpoint-suspended.gif
	deleted:    dist.java/java/img/icons/camel/breakpoint.gif
	deleted:    dist.java/java/img/icons/camel/camel.png
	deleted:    dist.java/java/img/icons/camel/camel_context_icon.png
	deleted:    dist.java/java/img/icons/camel/camel_route.png
	deleted:    dist.java/java/img/icons/camel/camel_route_folder.png
	deleted:    dist.java/java/img/icons/camel/camel_tracing.png
	deleted:    dist.java/java/img/icons/camel/channel24.png
	deleted:    dist.java/java/img/icons/camel/channelAdapter24.png
	deleted:    dist.java/java/img/icons/camel/channelPurger24.png
	deleted:    dist.java/java/img/icons/camel/choice24.png
	deleted:    dist.java/java/img/icons/camel/commandMessage24.png
	deleted:    dist.java/java/img/icons/camel/competingConsumers24.png
	deleted:    dist.java/java/img/icons/camel/component_folder.png
	deleted:    dist.java/java/img/icons/camel/contentBasedRouter24.png
	deleted:    dist.java/java/img/icons/camel/contentFilter24.png
	deleted:    dist.java/java/img/icons/camel/controlBus24.png
	deleted:    dist.java/java/img/icons/camel/convertBodyTo24.png
	deleted:    dist.java/java/img/icons/camel/correlationIdentifier24.png
	deleted:    dist.java/java/img/icons/camel/customDataFormat24.png
	deleted:    dist.java/java/img/icons/camel/datatypeChannel24.png
	deleted:    dist.java/java/img/icons/camel/deadLetterChannel24.png
	deleted:    dist.java/java/img/icons/camel/detour24.png
	deleted:    dist.java/java/img/icons/camel/distributionAggregate24.png
	deleted:    dist.java/java/img/icons/camel/documentMessage24.png
	deleted:    dist.java/java/img/icons/camel/durableSubscription24.png
	deleted:    dist.java/java/img/icons/camel/dynamicRouter24.png
	deleted:    dist.java/java/img/icons/camel/edit_camel_route.png
	deleted:    dist.java/java/img/icons/camel/encapsulatedSynchronous24.png
	deleted:    dist.java/java/img/icons/camel/endoints.png
	deleted:    dist.java/java/img/icons/camel/endpoint24.png
	deleted:    dist.java/java/img/icons/camel/endpointDrools24.png
	deleted:    dist.java/java/img/icons/camel/endpointFile24.png
	deleted:    dist.java/java/img/icons/camel/endpointFolder24.png
	deleted:    dist.java/java/img/icons/camel/endpointQueue24.png
	deleted:    dist.java/java/img/icons/camel/endpointRepository24.png
	deleted:    dist.java/java/img/icons/camel/endpointTimer24.png
	deleted:    dist.java/java/img/icons/camel/endpoint_folder.png
	deleted:    dist.java/java/img/icons/camel/endpoint_node.png
	deleted:    dist.java/java/img/icons/camel/endpoints/SAP24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/SAPNetweaver24.jpg
	deleted:    dist.java/java/img/icons/camel/endpoints/activemq24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/atom24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/bean24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/cxf24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/cxfrs24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/ejb24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/facebook24.jpg
	deleted:    dist.java/java/img/icons/camel/endpoints/file24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/ftp24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/ftps24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/imap24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/imaps24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/jdbc24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/jms24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/language24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/linkedin24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/log24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/mqtt24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/netty-http24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/netty24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/netty4-http24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/netty424.png
	deleted:    dist.java/java/img/icons/camel/endpoints/pop324.png
	deleted:    dist.java/java/img/icons/camel/endpoints/pop3s24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/quartz224.png
	deleted:    dist.java/java/img/icons/camel/endpoints/quartz24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/rss24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/salesForce24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/sap-netweaver24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/servlet24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/sftp24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/smtp24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/smtps24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/snmp24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/sql24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/timer24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/twitter24.png
	deleted:    dist.java/java/img/icons/camel/endpoints/weather24.jpg
	deleted:    dist.java/java/img/icons/camel/endpoints/xslt24.png
	deleted:    dist.java/java/img/icons/camel/enrich24.png
	deleted:    dist.java/java/img/icons/camel/envelopeWrapper24.png
	deleted:    dist.java/java/img/icons/camel/eventDrivenConsumer24.png
	deleted:    dist.java/java/img/icons/camel/eventMessage24.png
	deleted:    dist.java/java/img/icons/camel/fileTransfer24.png
	deleted:    dist.java/java/img/icons/camel/filter24.png
	deleted:    dist.java/java/img/icons/camel/flow24.png
	deleted:    dist.java/java/img/icons/camel/generic24.png
	deleted:    dist.java/java/img/icons/camel/guaranteedMessaging24.png
	deleted:    dist.java/java/img/icons/camel/idempotentConsumer24.png
	deleted:    dist.java/java/img/icons/camel/invalidMessageChannel24.png
	deleted:    dist.java/java/img/icons/camel/loadBalance24.png
	deleted:    dist.java/java/img/icons/camel/log24.png
	deleted:    dist.java/java/img/icons/camel/marshal24.png
	deleted:    dist.java/java/img/icons/camel/message24.png
	deleted:    dist.java/java/img/icons/camel/messageBroker24.png
	deleted:    dist.java/java/img/icons/camel/messageBus24.png
	deleted:    dist.java/java/img/icons/camel/messageDispatcher24.png
	deleted:    dist.java/java/img/icons/camel/messageExpiration24.png
	deleted:    dist.java/java/img/icons/camel/messageSelector24.png
	deleted:    dist.java/java/img/icons/camel/messageSequence24.png
	deleted:    dist.java/java/img/icons/camel/messageStore24.png
	deleted:    dist.java/java/img/icons/camel/messaging24.png
	deleted:    dist.java/java/img/icons/camel/messagingAdapter24.png
	deleted:    dist.java/java/img/icons/camel/messagingBridge24.png
	deleted:    dist.java/java/img/icons/camel/messagingGateway24.png
	deleted:    dist.java/java/img/icons/camel/multicast24.png
	deleted:    dist.java/java/img/icons/camel/node24.png
	deleted:    dist.java/java/img/icons/camel/normalizer24.png
	deleted:    dist.java/java/img/icons/camel/pipeline24.png
	deleted:    dist.java/java/img/icons/camel/pointToPoint24.png
	deleted:    dist.java/java/img/icons/camel/pollEnrich24.png
	deleted:    dist.java/java/img/icons/camel/pollingConsumer24.png
	deleted:    dist.java/java/img/icons/camel/process24.png
	deleted:    dist.java/java/img/icons/camel/processManager24.png
	deleted:    dist.java/java/img/icons/camel/processor24.png
	deleted:    dist.java/java/img/icons/camel/recipientList24.png
	deleted:    dist.java/java/img/icons/camel/requestReply24.png
	deleted:    dist.java/java/img/icons/camel/resequence24.png
	deleted:    dist.java/java/img/icons/camel/resume.gif
	deleted:    dist.java/java/img/icons/camel/returnAddress24.png
	deleted:    dist.java/java/img/icons/camel/route24.png
	deleted:    dist.java/java/img/icons/camel/routingSlip24.png
	deleted:    dist.java/java/img/icons/camel/setBody24.png
	deleted:    dist.java/java/img/icons/camel/sharedDatabase24.png
	deleted:    dist.java/java/img/icons/camel/smartProxy24.png
	deleted:    dist.java/java/img/icons/camel/split24.png
	deleted:    dist.java/java/img/icons/camel/step.gif
	deleted:    dist.java/java/img/icons/camel/storeInLibrary24.png
	deleted:    dist.java/java/img/icons/camel/suspend.gif
	deleted:    dist.java/java/img/icons/camel/testMessage24.png
	deleted:    dist.java/java/img/icons/camel/transactionalClient24.png
	deleted:    dist.java/java/img/icons/camel/transform24.png
	deleted:    dist.java/java/img/icons/camel/unmarshal24.png
	deleted:    dist.java/java/img/icons/camel/wireTap24.png
	deleted:    dist.java/java/img/icons/cassandra.svg
	deleted:    dist.java/java/img/icons/fabric8_icon.svg
	deleted:    dist.java/java/img/icons/messagebroker.svg
	deleted:    dist.java/java/img/icons/osgi/bundle.png
	deleted:    dist.java/java/img/icons/osgi/service.png
	deleted:    dist.java/java/img/icons/quartz/quarz.png
	deleted:    dist.java/java/img/kubernetes-Logo.svg
	deleted:    dist.java/java/img/kubernetes.svg
	deleted:    dist.java/java/img/logo-alt.svg
	deleted:    dist.java/java/img/logo-origin-thin.svg
	deleted:    dist.java/java/img/logo.svg
	deleted:    dist.java/java/img/spinner-inverse-lg.gif
	deleted:    dist.java/java/img/spinner-inverse-sm.gif
	deleted:    dist.java/java/img/spinner-inverse-xs.gif
	deleted:    dist.java/java/img/spinner-inverse.gif
	deleted:    dist.java/java/img/spinner-lg.gif
	deleted:    dist.java/java/img/spinner-sm.gif
	deleted:    dist.java/java/img/spinner-xs.gif
	deleted:    dist.java/java/img/spinner.gif
	deleted:    dist.java/java/index.html
	deleted:    dist.java/java/libs-a07e8842c6.js
	deleted:    dist.java/java/style.css
	deleted:    dist.java/java/version.json
	modified:   dist/scripts/scripts.js
	modified:   dist/scripts/vendor.js
	modified:   dist/styles/fonts/PatternFlyIcons-webfont.eot
	modified:   dist/styles/fonts/PatternFlyIcons-webfont.svg
	modified:   dist/styles/fonts/PatternFlyIcons-webfont.ttf
	modified:   dist/styles/fonts/PatternFlyIcons-webfont.woff
	modified:   dist/styles/main.css
	modified:   dist/styles/vendor.css
```

**Comment by spadgett** [comment]
I would remove the `dist.java` changes from your commit. Those shouldn't be there. If the other changes pass CI, we're good.

**Comment by cloudbehl** [comment]
@spadgett looks like build is passing on the local system by running `hack/verify-dist.sh` command. but travis CI is failing it.
Screenshot from 2019-05-22 21-51-42

**Comment by spadgett** [comment]
@cloudbehl can you try the steps here and see if you get the same output?

https://github.com/openshift/origin-web-console#debugging-dist-diff-failures

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by cloudbehl** [comment]
@spadgett Thanks for the fix, I wasn't able to fix it with the retry. looks like some deps are installed globally into the system and creating lots of conflicts. Thanks again!

**Pull request merged**
