### PR TITLE
Don't show image name multiple times when reused in a template

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/12006

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Looks like a travis flake

```
Warning: Running "copy:styles" (copy) task
Warning: Unable to create directory "/home/travis/build/openshift/origin-web-console/.tmp/styles" (Error code: EEXIST). Use --force to continue.

Aborted due to warnings.
```

**Comment by jwforres** [comment]
Yeah I've seen that same flake randomly on my local machine too.

**Pull request merged**
