### PR TITLE
Bug 1721428: Remove misleading "Metrics might not be available" warning

### PR DESCRIPTION
**Pull request by spadgett**
A metrics URL is not required to use HPAs. Since we can't reliably
detect whether metrics server is configured, remove the misleading
warning that might show up when HPAs will otherwise work.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1721428

/assign @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
Passed CI... @rhamilto can you tag again?

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
