### PR TITLE
Refactoring navbar to make space for additional utility icon (context…

### PR DESCRIPTION
**Pull request by rhamilto**
… switcher)

Note:  these screenshots include a placeholder for the context switcher, but this PR does not contain the context switcher itself.  This PR is just prep work for the forthcoming context switcher (which will be in a separate PR).

@jwforres, does the placement and style of the context switcher look correct?

Before:

screen shot 2017-03-22 at 2 29 21 pm
screen shot 2017-03-22 at 2 29 30 pm
screen shot 2017-03-22 at 2 29 37 pm
screen shot 2017-03-22 at 2 30 04 pm
screen shot 2017-03-22 at 2 29 51 pm

screen shot 2017-03-22 at 2 23 43 pm
screen shot 2017-03-22 at 2 23 57 pm
screen shot 2017-03-22 at 2 24 09 pm
screen shot 2017-03-22 at 2 25 56 pm
screen shot 2017-03-22 at 2 26 17 pm

After:

screen shot 2017-03-22 at 2 14 04 pm
screen shot 2017-03-22 at 2 14 15 pm
screen shot 2017-03-22 at 2 14 22 pm
screen shot 2017-03-22 at 2 14 31 pm
screen shot 2017-03-22 at 2 15 04 pm
screen shot 2017-03-22 at 2 15 41 pm
screen shot 2017-03-22 at 2 15 33 pm
screen shot 2017-03-22 at 2 22 13 pm
screen shot 2017-03-22 at 2 15 26 pm
screen shot 2017-03-22 at 2 15 15 pm

### CODE REVIEW

**Comment by jwforres** [comment]
@lizsurette for the question on whether the placement / visuals on the application switcher look right (this is the 3.6 version before the major nav changes)

**Comment by lizsurette** [comment]
@jwforres Looks good to me!! @serenamarie125 Do you have a preference if the "warning/notification" icon is first or if the switcher should be first in order?

**Comment by rhamilto** [comment]
> @jwforres Looks good to me!! @serenamarie125 Do you have a preference if the "warning/notification" icon is first or if the switcher should be first in order?

We can't easily change the order of the warning and switcher icons, so I hope the order is ok!

**Comment by spadgett** [comment]
Is the context switcher under the hamburger menu at mobile?

**Comment by rhamilto** [comment]
> Is the context switcher under the hamburger menu at mobile?

Per @jwforres, that's the plan.

**Comment by spadgett** [comment]
[merge]

**Comment by lizsurette** [comment]
@spadgett yes, exactly it will be available between notifications and help under the hamburger menu.

**Pull request merged**
