### PR TITLE
Increase spacing beneath traffic-table and help text.

### PR DESCRIPTION
**Pull request by sg00dwin**
screen shot 2017-01-04 at 1 46 35 pm

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett 
Fixes https://github.com/openshift/origin-web-console/issues/1064

**Comment by spadgett** [comment]
Nit, but I think it's a bit too much bottom margin for the traffic table since the text is describing resources in the table. I might use something like 5px.

"Show Annotations" is different since it's not related to the pods table.

 @rhamilto opinion?

**Comment by rhamilto** [comment]
> @rhamilto opinion?

I'm ok with it as is because it's still reads as part of the "Traffic" section.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
