### PR TITLE
Fix storage capacity values on  Storage page table view

### PR DESCRIPTION
**Pull request by zherman0**
The storage capacity is no longer being returned in the API call for PVCs.  I have changed the table view of the pvc values so that the "Capacity" column gets it value from the requests[storage] instead of capacity[storage].  I cannot find anything in the docs that says this was an intentional change to the API but I thought it was best to have this working properly.

### CODE REVIEW

**Comment by spadgett** [comment]
Hm, I still see it in the API.

https://github.com/openshift/origin/blob/master/vendor/k8s.io/kubernetes/pkg/api/v1/types.go#L483

It looks like status shows the actual capacity whereas spec shows what was requested.

/cc @fabianofranz

**Comment by zherman0** [comment]
Ok, well, I am not sure what is going on.  I am running the latest code for OSE and the API does not seem to be working on the UI or Cmd Line when it comes to that capacity value.  Thanks for looking at this though.  I will investigate further.

**Comment by spadgett** [comment]
@zherman0 Can you share the YAML of the PVC you're looking at?

```
$ oc get pvc [name] -o yaml -n [project]
```

**Comment by zherman0** [comment]
@spadgett 
Here is my investigation between my 2 VM's of OSE.  I list the versions on top.  I am thinking maybe there is a bug with the latest OSE/Kub. My latest was pulled yesterday morning.  Notice that after things get bound, there is no capacity in the status.

OLDER BUILD
oc v1.3.0-alpha.1-62-g504ea97
kubernetes v1.3.0-alpha.1-331-g0522e63

Before Bound
 oc get pvc captest-oldsystem -o yaml -n default
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2016-07-22T15:56:58Z
  name: captest-oldsystem
  namespace: default
  resourceVersion: "126674"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/captest-oldsystem
  uid: eb6b7294-5024-11e6-a0d1-52540063cc63
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status:
  phase: Pending

AFTER
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2016-07-22T15:56:58Z
  name: captest-oldsystem
  namespace: default
  resourceVersion: "126679"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/captest-oldsystem
  uid: eb6b7294-5024-11e6-a0d1-52540063cc63
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: nfs-ct
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  phase: Bound

+++++++++++++++++++++++++++++++++
NEWEST
oc v1.3.0-alpha.2+6a5f284
kubernetes v1.3.0+57fb9ac
Before Bind
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: 2016-07-22T15:54:17Z
  name: captest1
  namespace: default
  resourceVersion: "39291"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/captest1
  uid: 8b9bd6b9-5024-11e6-bdf5-525400e8bb0f
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
status:
  phase: Pending

AFTER BOUND

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2016-07-22T15:54:17Z
  name: captest1
  namespace: default
  resourceVersion: "39342"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/captest1
  uid: 8b9bd6b9-5024-11e6-bdf5-525400e8bb0f
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: oc-pvcap
status:
  phase: Bound

**Comment by spadgett** [comment]
@markturansky Is this expected?

**Comment by markturansky** [comment]
The PV controller was rewritten for Kube 1.3.  It might be a bug that Status capacity is not being set with the actual value the PV provides.  

It is expected that the actual value is shown after binding, not the requested value.

**Comment by spadgett** [comment]
@markturansky Thanks, should this be an origin issue then?

**Comment by markturansky** [comment]
No, it'd be an upstream bug.

**Comment by zherman0** [comment]
An issue has been opened against K8s for this.  I guess we should just close this out.

**Pull request closed without merging**
