### PR TITLE
Make tags wider in image stream listing table

### LINKED ISSUE #1848: Image stream tags cropped too short
In building images for origin inside origin, I need to create image tags that have the name of the origin image. However, when displaying them in the web console, the tags are cropped too small:
image

### PR DESCRIPTION
**Pull request by spadgett**
Doubles the width of the tags in the table. There is a `title` attribute if it still gets clipped.

Fixes #1848

### CODE REVIEW

**Comment by spadgett** [comment]
Before:

openshift web console 2017-07-14 12-31-11

After:

openshift web console 2017-07-14 12-31-34

**Comment by jwforres** [comment]
how is that behaving at mobile? i know that is where we had some issues related to those tags

**Comment by jwforres** [comment]
I also don't love how it looks at that width :-\  most tags are actually short

**Comment by jwforres** [comment]
maybe somewhere in the middle?

**Comment by spadgett** [comment]
Here is somewhere in between:

openshift web console 2017-07-14 13-25-02

Really I think the table column should grow/shrink to fit the content, but that change probably needs to happen upstream in registry-image-widths

**Comment by spadgett** [comment]
> how is that behaving at mobile? i know that is where we had some issues related to those tags

Not great. I'm not sure if we can fix that without an upstream fix though.

openshift web console 2017-07-14 13-27-19

**Comment by jwforres** [comment]
[merge][severity:blocker]

**Comment by spadgett** [comment]
[merge][severity: blocker]

**Pull request merged**
