### PR TITLE
Resize monitoring metrics charts when sidebar is expanded or collapsed

### LINKED ISSUE #249: Monitoring page: sparklines don't resize when events sidebar shown or hidden
openshift_web_console

### PR DESCRIPTION
**Pull request by jwforres**
Fixes #249

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by spadgett** [comment]
[merge]

**Comment by jwforres** [comment]
whoops updated it to flush after you tagged it, will have to re-tag it after the merge fails on the commit mismatch

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
