### PR TITLE
Bump openshift jvm to 1.0.50

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1380392
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1380421

### CODE REVIEW

**Comment by jwforres** [comment]
@alexkieling @astefanutti this diff is quite large, was all of this really necessary to fix the two referenced bugs.  This would be fine going into the master stream for 1.4+ but its a lot of changes to be backporting.

**Comment by alexkieling** [comment]
@jwforres the changed files you see are not related to the two referenced bugs. I will work with @astefanutti to fix the PR.

**Comment by aileenc** [comment]
What version of openshift jvm does the console currently use?

**Comment by jwforres** [comment]
1.0.47

But the issue is not bumping openshift-jvm itself, I dug into the nested dependency change for hawtio-integration going from 2.0.20 to 2.0.21, there are other commits that were not in 2.0.20 that are included in 2.0.21 that are not part of this fix.

**Comment by alexkieling** [comment]
@jwforres You are right. Sorry for the trouble. We'll release a new version of hawtio-integration with only the bug fixes.

**Comment by jwforres** [comment]
awesome thanks @alexkieling

**Comment by jwforres** [comment]
@alexkieling i'm still seeing a bunch of changes to image files and CSS

**Comment by alexkieling** [comment]
@jwforres please check you are pointing to https://github.com/hawtio/openshift-jvm/releases/tag/v1.0.49

**Comment by jwforres** [comment]
@alexkieling sorry about that needed to do a clean, something we fixed in our build process in the master branch.  I do still see CSS changes, expected?

**Comment by alexkieling** [comment]
@jwforres The bower dependencies specify version ranges using the `~` symbol, which caused some dependencies to be upgraded. We defined the exact versions you currently have to avoid that from happening. Please use the new release v1.0.50.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
