### PR TITLE
Update key-value-editor instances to use add-row-link

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fix #1366457 (bugzilla)
Fixes the lingering input issues by adding the manual "add X" link.

@jwforres

### CODE REVIEW

**Comment by jwforres** [comment]
changes LGTM but you have a merge conflict, probably with the dist

**Comment by benjaminapetersen** [comment]
heh yup and i had even just rebased :smile:

**Comment by benjaminapetersen** [comment]
rebased!
[test]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
> Built dist does not match what is committed, run 'grunt build' and include the results in your commit.

**Comment by benjaminapetersen** [comment]
oop, forgot `install-deps` on that one. one more time...

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
