### PR TITLE
Bumping dependency version in bower.json

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Currently only bumping `common`
@sg00dwin's PR's still open in patternfly, so not yet included:
- https://github.com/patternfly/patternfly/pull/749
- https://github.com/patternfly/patternfly/pull/748

Do we want to wait for these items? Also have some resolution issues 
between console/common.

@spadgett @sg00dwin

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Haven't built yet due to:

```
Unable to find a suitable version for kubernetes-label-selector, please choose one by typing one of the numbers below:
    1) kubernetes-label-selector#2.0.0 which resolved to 2.0.0 and is required by origin-web-console
    2) kubernetes-label-selector#~2.1.1 which resolved to 2.1.1 and is required by origin-web-common#0.0.57
```
Can we open this up to accept a range with one of the repos, prob common?

**Comment by spadgett** [comment]
We should update that dependency in console.

@benjaminapetersen I'm working on a catalog release so we can bump everything at once.

**Comment by benjaminapetersen** [comment]
@spadgett sounds good

**Comment by spadgett** [comment]
https://github.com/openshift/origin-web-catalog/pull/439

**Comment by spadgett** [comment]
origin-web-catalog 0.0.46 published

**Comment by benjaminapetersen** [comment]
Updated.

**Comment by benjaminapetersen** [comment]
`patternfly` and `angular-patternfly` bumped as well.

**Comment by spadgett** [comment]
Need to bump kubernetes-label-selector to 2.1.1

**Comment by spadgett** [comment]
Remove patternfly resolution. I don't think it's needed anymore.

**Comment by benjaminapetersen** [comment]
Great, will do.  Slowly whittling them down...

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
