### PR TITLE
Fix broken route links

### PR DESCRIPTION
**Pull request by sg00dwin**
Noticed a couple of broken links to docs for routes.

### CODE REVIEW

**Comment by spadgett** [comment]
/kind bug
/lgtm
/hold

Holding for @jwforres approval, but this is probably a blocker.

**Comment by jwforres** [comment]
yup
/hold cancel

but @sg00dwin can you do a pass on the rest of the links and make sure they are still good

**Comment by jwforres** [comment]
@ahardin-rh there are at least two cases here where doc links are broken, these should have at least had redirects put in place

**Comment by sg00dwin** [comment]
@jwforres All other links referenced in https://github.com/openshift/origin-web-console/blob/master/app/scripts/constants.js are good

**Pull request merged**
