### PR TITLE
Data service List method returns a promise, passing callback as a param now optional

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin-web-console/issues/728

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

**Comment by jwforres** [comment]
@benjaminapetersen @sub-mod FYI

**Comment by benjaminapetersen** [comment]
Nice, looks good to me.  I wasn't super excited to volunteer to figure this one out. :smile:

**Comment by jwforres** [comment]
i'd like to deprecate passing the callback in, but not till we get a chance to quit using it ourselves

**Comment by jwforres** [comment]
@spadgett updated based on our discussion

**Comment by benjaminapetersen** [comment]
Hmm. I'd be good with you adding a deprecation warning now & then we could make an issue w/a list of `DataService.list()` calls to fix (I'll even volunteer to do that part).

**Comment by jwforres** [comment]
i would want to do a deprecation warning as a console.warning so extensions
writers are aware of it without turning on our Logger, and i don't want
that happening with our OOTB product calls, would rather wait till ours are
taken care of

**Comment by benjaminapetersen** [comment]
Ah, that makes sense.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
