### PR TITLE
Wrap limit ranges section on quota page so it can be easily hidden with custom CSS

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1387440

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL, the diff is primarily a whitespace change

**Comment by jwforres** [comment]
@luciddreamz FYI

**Comment by spadgett** [comment]
[merge]

**Comment by jwforres** [comment]
@luciddreamz in the mean time you could do a hacky text content based css selector to hide that Limit Range header :-\  this fix is going into 3.4

**Pull request merged**
