### PR TITLE
Rework nav to remove :hover selectors to address bugs, inconsistencies

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #2373

Building on what @sg00dwin did in https://github.com/sg00dwin/origin-web-console/tree/vertical-nav-tab-issue2373%23issuecomment-339359101, this removes all :hover styling changes in order to forge consistency across hover, click, and tab navigation.  

@sg00dwin, @spadgett, mind pulling these changes, testing, and seeing if everything is ok?

### CODE REVIEW

**Comment by rhamilto** [comment]
@jwforres, would love your keen eyes on this, too.

**Comment by sg00dwin** [comment]
@rhamilto I don't see any issue with either the mouse or tab navigation behavior.  Looks good!

**Comment by rhamilto** [comment]
I just force pushed some changes, so if you already pulled, delete your branch and recreate.

**Comment by spadgett** [comment]
Works great, @rhamilto

**Pull request merged**
