### PR TITLE
Fix for created date not wrapping well with "Add to Application" button

### LINKED ISSUE #2060: Created date does not wrap well with "Add to Application" button
openshift web console 2017-09-12 18-39-44

cc @jeff-phillips-18

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #2060

screen shot 2017-09-13 at 11 41 53 am

### CODE REVIEW

**Comment by spadgett** [comment]
@rhamilto I wonder if we should add `nowrap` around the "created ..." message, but I'm sure that impacts a lot of pages.

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by spadgett** [comment]
> Origin Web Console Merge Results: FAILURE (https://ci.openshift.redhat.com/jenkins/job/merge_pull_request_origin_web_console/188/) (Base Commit: f3fcba9) (PR Branch Commit: f5c5b51) (Extended Tests: bug)

Flake #2016, which is hopefully fixed by #2064. Will retag when #2064 merges

**Comment by spadgett** [comment]
[merge][severity: bug]

**Comment by rhamilto** [comment]
> @rhamilto I wonder if we should add nowrap around the "created ..." message, but I'm sure that impacts a lot of pages.

Yeah.  I went for the simpler fix since this only occurs roughly around 800px - 900px.

**Comment by spadgett** [comment]
Works for me, thanks

**Pull request merged**
