### PR TITLE
Tweaking the catalog scrollbar colors

### LINKED ISSUE #1488: [WIP] Catalog scrollbar variations
@serenamarie125 [asked for the inner scrollbar within the catalog landing page to be tweaked](https://github.com/openshift/origin-web-catalog/issues/182#issuecomment-297999532).  Below is the existing as well as an inverse option in addition to a blue option.  Thoughts?

Note:  I tried a middle gray color, but it looked like it belonged to the sidebar rather than the main content area.

Default (as it exists today):

screen shot 2017-04-28 at 1 44 01 pm

Inverse:

screen shot 2017-04-28 at 1 37 36 pm

Blue:

screen shot 2017-04-28 at 1 43 36 pm

@spadgett, @jwforres, @sg00dwin, @beanh66, @ncameronbritt

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1488 

screen shot 2017-04-28 at 1 43 36 pm

screen shot 2017-05-01 at 4 00 08 pm

Note:  I also tested this color with the alternate background image, and blue looks good as there well.

### CODE REVIEW

**Comment by spadgett** [comment]
Should the project sidebar scrollbar be a dark gray color instead of blue?

screen shot 2017-05-01 at 3 09 44 pm

**Comment by rhamilto** [comment]
> Should the project sidebar scrollbar be a dark gray color instead of blue?

Nope.  That's a bug.  Lemme fix.

**Comment by rhamilto** [comment]
> That's a bug. Lemme fix.

Fixed

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
