### PR TITLE
Bug 1444200 - Fix problem showing template descriptions

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1444200

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
```
CreateFromURLPage.visit(): url: create?imageStream=nodejs&imageTag=4&name=nodejs-edited&sourceURI=https://github.com/openshift/nodejs-ex.git-edited&sourceRef=master-edited&contextDir=/-edited&namespace=template-dumpster
A Jasmine spec timed out. Resetting the WebDriver Control Flow.
```

I'm not able to run `grunt test-integration` on my laptop. I ran this test manually, and it worked.

[merge]

**Comment by spadgett** [comment]
The problem is the test is trying to open this URL.

screen shot 2017-04-21 at 8 05 00 am

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
@jwforres I verified the three failing tests manually.

I verified the tests fail in Jenkins without this change as well (#1459)

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
