### PR TITLE
Replacing deprecated grunt-autoprefixer with postcss

### LINKED ISSUE #1337: grunt-autoprefixer is very outdated
We're currently 13 releases behind the most recent release of [grunt-autoprefixer](https://github.com/nDmitry/grunt-autoprefixer).  We should probably update.

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes #1337

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM surprised there are no changes to the dist as a result

**Comment by rhamilto** [comment]
>  LGTM surprised there are no changes to the dist as a result

I was, too!  I even made a less change to ensure it was true.

**Comment by spadgett** [comment]
It's still using the same autoprefixer under the covers, correct? It's just changing the grunt task that runs the prefixer?

**Comment by rhamilto** [comment]
> It's still using the same autoprefixer under the covers, correct? It's just changing the grunt task that runs the prefixer?

Yep

**Comment by jwforres** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Huh. that was less painful than expected for sure.

**Pull request merged**
