### PR TITLE
Update kve to 1.2.3, fixes tab & focus issues

### LINKED ISSUE #252: Environment variable editor grabs focus always on page load
On some forms, this causes the page to scroll to the bottom on page load.

/cc @jwforres @benjaminapetersen

### LINKED ISSUE #257: Accessibility: Impossible to tab past env variable editor
If I try to tab through the env var editor, it just keeps creating new rows. There is no way using only the keyboard to get to later form fields.

openshift_web_console

Making a P1 because it breaks accessibility.

/cc @benjaminapetersen @jwforres

### PR DESCRIPTION
**Pull request by benjaminapetersen**
- fixes #252 where kve always grabs focus on load
- fixes #257 where kve does not allow tabbing past its internal inputs

I need to test this within the web console yet since I didn't have my env up and running, but both issues working now in my standalone test pages.

@jwforres @spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
@benjaminapetersen tried this in the web console, and it works

[merge]

**Comment by benjaminapetersen** [comment]
@spadgett awesome, thx!

**Comment by benjaminapetersen** [comment]
flake :/

**Comment by spadgett** [comment]
```
PhantomJS 1.9.8 (Linux) ERROR
  Error: [$injector:modulerr] Failed to instantiate module openshiftConsole due to:
  Error: [$injector:modulerr] Failed to instantiate module key-value-editor due to:
  Error: [$injector:nomod] Module 'key-value-editor' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
  http://errors.angularjs.org/1.3.20/$injector/nomod?p0=key-value-editor
```

**Comment by spadgett** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
I think I can help babysit this now actually... lets see if it works!
[merge]

**Comment by spadgett** [comment]
karma.conf is loading the minified JS, but I don't see it in the angular-key-value-editor repo dist.

https://github.com/openshift/origin-web-console/blob/master/test/karma.conf.js#L56

**Comment by benjaminapetersen** [comment]
Ah, bother, I must have killed the server before the last build ran. Just a sec.

**Comment by benjaminapetersen** [comment]
[TEST]

**Comment by jwforres** [comment]
looks like test worked [merge]

**Pull request merged**
