### PR TITLE
Bug 1505281 - Improve import YAML results message

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1505281
See also #2217 

List:

openshift web console 2017-11-01 13-30-16

Single resource:

openshift web console 2017-11-01 13-46-08

/kind bug

cc @rhamilto @jwforres

### CODE REVIEW

**Comment by spadgett** [comment]
Still testing the different scenarios

**Comment by spadgett** [comment]
No change to processed templates:

openshift web console 2017-11-01 13-54-37

**Comment by jwforres** [comment]
lgtm but
/hold
till you are done testing

**Comment by jwforres** [comment]
guess i could've actually, still getting use to these fancy new options
/lgtm

**Comment by spadgett** [comment]
Found a bug (#2427), but I think it's unrelated to this change.

**Comment by spadgett** [comment]
Rebased and rebuilt. Removing WIP.

/hold cancel

**Comment by spadgett** [comment]
Reproduced #2427 without these changes.

**Comment by spadgett** [comment]
Adding back the lgtm label since the last changes were a rebase only

**Pull request merged**
