### PR TITLE
Bug 1795930: Update jQuery to v3.4.0

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1795930

### CODE REVIEW

**Comment by spadgett** [comment]
This bug only applies to 3.11.z since the 4.x console has a different code base. Manually adding the valid-bug label.

**Review by spadgett — APPROVED** [review]
/approve
/lgtm

**Review by benjaminapetersen — COMMENTED** [review]
👍

**Pull request merged**
