### PR TITLE
Fix screenshots for test descriptions with special characters

### PR DESCRIPTION
**Pull request by spadgett**

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[test]

**Comment by jwforres** [comment]
we should trim leading/trailing whitespace too, im seeing some files in the output where the filename has a leading space

**Comment by spadgett** [comment]
Yeah was just noticing that.

**Comment by spadgett** [comment]
@jwforres PTAL

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
