### PR TITLE
Publish kubevirt image for the kubevirt-apb to use

### PR DESCRIPTION
**Pull request by rthallisey**

### CODE REVIEW

**Comment by rhamilto** [comment]
Ideally a monochrome version of the logo would also be added to https://github.com/openshift/openshift-logos-icon.  To make a long story short, we originally started with monochrome and then added the [option for color overrides](https://github.com/openshift/origin-web-console/blob/master/app/scripts/constants.js#L593-L667).  I am happy to make the necessary update to openshift-logos-icon; however, I will need a version of [the SVG of the logo](https://github.com/kubevirt/community/blob/master/logo/kubevirt-pre.svg) that has fonts converted to outlines.  @fabiand, can you or someone with the required font make that update to the SVG?  That same corrected SVG is the ideal choice to add in this PR since SVGs are resolution independent.

**Comment by fabiand** [comment]
Ah, a good hint to convert the font. Let me do this update right away.

**Comment by rthallisey** [comment]
@rhamilto Here's another PR for VM logos if you don't mind review that too: https://github.com/openshift/origin-web-console/pull/2938

**Comment by rhamilto** [comment]
@rthallisey, I've got the [monochrome logo update in flight](https://github.com/openshift/openshift-logos-icon/pull/14).  Can you update this PR to update the [LOGOS object with the new key/value pair for this logo](https://github.com/openshift/origin-web-console/blob/master/app/scripts/constants.js#L630)?

**Comment by rhamilto** [comment]
@rthallisey, additionally, kubevirt.svg should also be added in app/images/logos.  The copy in dist gets added during build.

**Comment by jniederm** [comment]
Cherry-picked to demo branch as https://github.com/jniederm/origin-web-console/commit/70437d7dff56478df4e912f3db81676bdcba7133

**Comment by rhamilto** [comment]
@rthallisey, can you update this PR so I can final review/merge?  You simply need to move kubevirt.svg to app/images/logos, run `grunt build` (which will create the copy of kubevirt.svg in dist/images/logos) and amend your commit.

**Comment by rthallisey** [comment]
@rhamilto updated.

**Comment by rhamilto** [comment]
@rthallisey, it looks like you changed the file format to png?  [svg]https://github.com/kubevirt/community/blob/master/logo/kubevirt-pre.svg) is preferred.

**Pull request merged**
