### PR TITLE
Add tech preview header to StatefulSets list & detail page

### PR DESCRIPTION
**Pull request by benjaminapetersen**
screen shot 2017-01-31 at 11 35 37 am
screen shot 2017-01-31 at 11 35 43 am

@jwforres @spadgett

### CODE REVIEW

**Comment by jwforres** [comment]
Looks like the placement has gotten off in the second screenshot

**Comment by benjaminapetersen** [comment]
Hmm... yeah, one has `middle-header` the other has `middle-header header-toolbar` as parents.

**Comment by benjaminapetersen** [comment]
@jwforres actually, its just that the first one has the scrollbar but I didn't include it in the screenshot.

screen shot 2017-01-31 at 4 49 01 pm

**Comment by benjaminapetersen** [comment]
screen shot 2017-01-31 at 5 03 54 pm

Adjusted list view.

**Comment by jwforres** [comment]
still doesn't seem right, that is adding a bunch of top whitespace that
wasnt there before

**Comment by benjaminapetersen** [comment]
screen shot 2017-02-01 at 10 10 20 am

:grin::grin::grin:

**Comment by jwforres** [comment]
thanks! [merge]

**Comment by jwforres** [comment]
@sspeiche tech preview indicator is going in

**Pull request merged**
