### PR TITLE
Fix a minor typo

### PR DESCRIPTION
**Pull request by xingxingxia**
@spadgett Please have a check, thanks!

### CODE REVIEW

**Comment by spadgett** [comment]
@xingxingxia Thanks, can you run `grunt build` to create the dist file?

**Comment by xingxingxia** [comment]
@spadgett hmm, not clear what to do :) Where to run `grunt build` and get the dist file? After getting the dist file, what further to do?

**Comment by spadgett** [comment]
@xingxingxia Please see the contributing section of the README:

https://github.com/openshift/origin-web-console#contributing

Once you install the dependencies, you can run `grunt build`, which creates files in the `dist` folder. This should be included in your Git commit.

**Comment by xingxingxia** [comment]
@spadgett Updated, please check. Thx for the guide

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
