### PR TITLE
[stage] Bug 1498897 - Don't break if quota status is not set

### PR DESCRIPTION
**Pull request by spadgett**
Fixes a runtime error in the console checking resource quota when the quota status has not been set.

https://bugzilla.redhat.com/show_bug.cgi?id=1498897

See also #2216

cc @jupierce

### CODE REVIEW

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
> Can't open user config file ./.config/origin-ci-tool/inventory/.ssh_config: No such file or directory
> FINISHED STAGE: FAILURE: FORWARD PARAMETERS TO THE REMOTE HOST [00h 00m 00s]

[merge]

**Comment by spadgett** [comment]
@stevekuznetsov Merges aren't working for the origin-web-console stage branch. Any ideas?

> Can't open user config file ./.config/origin-ci-tool/inventory/.ssh_config: No such file or directory

**Comment by stevekuznetsov** [comment]
@jupierce 

```
[ERROR] No approval criteria are configured for 'stage' branch of 'origin-web-console' repo.
```

**Comment by jupierce** [comment]
@stevekuznetsov  Thanks. @spadgett fixed. 
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
