### PR TITLE
Switch inactivity timeout to use new config value

### PR DESCRIPTION
**Pull request by spadgett**
origin-web-console-server PR: https://github.com/openshift/origin-web-console-server/pull/22

https://trello.com/c/JNf6bKET

/assign @jwforres 
/cc @jhadvig 

/hold

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM, let me know when you want final review

**Comment by spadgett** [comment]
Rebased and added the setting to app/config.js. This is just waiting on openshift/origin-web-console-server#22 now.

/hold

**Comment by jwforres** [comment]
/lgtm

So it can go whenever you take off the hold

**Pull request merged**
