### PR TITLE
Only show service catalog resources when available

### PR DESCRIPTION
**Pull request by spadgett**
This lets us show the new landing page without the service catalog running.

See also https://github.com/openshift/origin-web-catalog/pull/241

### CODE REVIEW

**Comment by jwforres** [comment]
Just double checking, you don't see Create Binding in the kebab actions for deployments right.  I think we hid it there weren't any services.

**Comment by spadgett** [comment]
Yeah I tested it. We only show it if pod_presets is on and there are service instances (which will be empty if the service catalog isn't running).

**Comment by spadgett** [comment]
https://github.com/openshift/origin-web-console/blob/master/app/views/overview/_list-row-actions.html#L28

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
