### PR TITLE
Fix for create project dialog in projects list for mobile.

### LINKED ISSUE #2441: Create Project dialog button is cut off
The create project dialog from the project list (not the landing page) is too wide for the screen.

iphone x - ios 11 0 2017-11-02 13-22-04

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes #2441

### CODE REVIEW

**Comment by spadgett** [comment]
/kind bug
/lgtm
/hold

@jwforres ok to merge?

**Comment by jwforres** [comment]
yep low risk
/hold cancel

**Pull request merged**
