### PR TITLE
Fix wrong word Succesfully

### PR DESCRIPTION
**Pull request by yapei**
A tiny fix for https://bugzilla.redhat.com/show_bug.cgi?id=1482464

Trying to submit one little PR and it's the first time of creating pull request here, please point me at any incorrectness, thanks

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by amarie401** [comment]
@yapei there is also another instance of the misspelling in ```addConfigVolume.js``` as well

**Comment by spadgett** [comment]
@yapei You'll need to run `hack/install-deps.sh` and `grunt build` to create the dist files. Thanks!

**Comment by yapei** [comment]
@spadgett  Submitted requested changes, thanks

**Comment by spadgett** [comment]
[merge][severity: bug]

**Pull request merged**
