### PR TITLE
Add support for AMQ 7 Broker in Java console (3.11)

### PR DESCRIPTION
**Pull request by abkieling**
A new release of hawtio/openshift-jvm has been made to include the hawtio-artemis plugin, which adds support for AMQ 7 Brokers.

### CODE REVIEW

**Comment by spadgett** [comment]
@alexkieling Can you remove package-lock.json? I know it's typically checked in, but it was causing problems for us (see #3012)

**Comment by abkieling** [comment]
@spadgett Shall I add it to .gitignore?

**Comment by spadgett** [comment]
Yeah, sounds good.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by abkieling** [comment]
This one needs an OK to test, I think.

**Pull request merged**
