### PR TITLE
Bug 1461702 - Fix display of build webhooks to support new types

### PR DESCRIPTION
**Pull request by jwforres**
Also fixes outdated documentation links.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1461702

### CODE REVIEW

**Comment by jwforres** [comment]
The build-config.html diff looks big because i fixed an indention issue with that section of the template

**Comment by spadgett** [comment]
We had a lot of broken links :(

**Comment by spadgett** [comment]
[merge][severity: blocker]

**Comment by jwforres** [comment]
hmm, travis is fine with the dist but jenkins failed on main.css, it looks right to me though...

lemme kick it again and see what happens

[merge][severity: blocker]

**Comment by jwforres** [comment]
@spadgett concerned that this keeps getting a CSS dist in Jenkins, and only Jenkins...

**Comment by spadgett** [comment]
We might start printing the content of the diff instead of just the files so we know what's really different.

**Comment by jwforres** [comment]
added a commit to switch to use git diff
[test]

**Pull request merged**
