### PR TITLE
 Virtual Machines views

### PR DESCRIPTION
**Pull request by jniederm**
Only the last commit is relevant. The preceding one is to express dependency on #2966.

---

This patch extends viewing of Kubevirt virtual machines (VMs)
in Overview page by separate listing page and detail page.

* Menu > Applications > Virtual Machines entry added
* Page listing both vms (`virtualmachine` Openshift resource) and ovms
  (`offlinevirtualmachine` Openshift resource).
* vms and ovms are not listed in Menu > Resources > Other resources page
* Page showing detail of either vm or ovm or combination of ovm+vm. vm
  only variant is called "transient" in the UI.
* Click to VM name in Overview page now leads to a VM detail page.

Detail page shows labels of vm and ovm entities and 3 tabs:
* Detail
  showing VM state, uptime (based on container uptime), name of host the
  VM is running on, link to pod running the VM, memory and guest
  operating system. Differences in configuration between vm and ovm are
  highlighted.
* Logs
  Logs of container currently running the vm.
* Events
  Events of entities ovm, vm and pods that run (or ran) the vm.

Dropdown actions of the VM detail page:
* Start
* Restart
* Stop
* Edit VM YAML
* Edit OVM YAML
* Delete

Common parts of Overview page and VM detail page shares code.

---

The PR is available as [`docker.io/jniederm/origin-web-console:pr3002-1`][1] deployable to openshift 3.10 using commands

[1]: https://hub.docker.com/r/jniederm/origin-web-console/tags/

```
oc login -u system:admin
oc set image deployment/webconsole webconsole=docker.io/jniederm/origin-web-console:pr3002-1 -n openshift-web-console
```

### Screenshots:
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by jniederm** [comment]
@jhadvig please have a look

**Comment by serenamarie125** [comment]
We talked about this in today's CNV daily meeting.  We are going to keep this PR open until we do more validation on the design.  @beanh66 is preparing 2 different sets of designs for this scenario, and will be sending out a survey to get some feedback on which way we should go.  

This PR shouldn't be merged until we get these results back - the thought is that we will have this info next week.

**Comment by jwforres** [comment]
Please keep in mind *everything* that is done here would only be valid for about one release and will all have to be migrated to the new console code base. This PR / feature set is getting quite large.

**Comment by jniederm** [comment]
> Please keep in mind everything that is done here would only be valid for about one release and will all have to be migrated to the new console code base. This PR / feature set is getting quite large.

We are ready to reimplement this functionality in *console* project.

**Comment by jniederm** [comment]
Deprecated in favor of #3006.

**Pull request closed without merging**
