### PR TITLE
Remove tech preview from stateful sets pages

### LINKED ISSUE #2745: Remove tech preview label from stateful sets page
/assign @benjaminapetersen 
/area techdebt

### PR DESCRIPTION
**Pull request by benjaminapetersen**
Fixes #2745

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Can do, this should be in `.gitignore` correct? I forget why these show up

**Comment by benjaminapetersen** [comment]
removed.

**Comment by spadgett** [comment]
>  this should be in .gitignore correct?

No, the file is meant to be tracked.

> I forget why these show up

Probably because you clean installed assets or ran npm update.

**Pull request merged**
