### PR TITLE
[enterprise-3.10] Bug 1607150 - UI Timeout causing IE 11 to automatically log out

### PR DESCRIPTION
**Pull request by jhadvig**
manually backporting https://github.com/openshift/origin-web-console/pull/3041

@spadgett fyi

### CODE REVIEW

**Comment by spadgett** [comment]
> ci/openshift-jenkins — Skipped

@stevekuznetsov Do you know why the tests aren't running on this branch? I'm not sure what changed, but this used to work.

**Comment by spadgett** [comment]
/hold
because the tests aren't running

**Comment by stevekuznetsov** [comment]
There is one test that is configured for `release-3.10` branch -- should that be `enterprise-3.10`? See: https://github.com/openshift/release/blob/master/cluster/ci/config/prow/config.yaml#L2146

**Comment by spadgett** [comment]
@stevekuznetsov Is there a way to say it should run for all branches? It should run for at least `enterprise-3.*`. I believe this is how it worked before.

**Comment by spadgett** [comment]
Not sure if this changed with https://github.com/openshift/release/commit/14c67661df00bc784082a1f69a65d412d3496d37

**Comment by stevekuznetsov** [comment]
Edited the branch name in https://github.com/openshift/release/pull/1102 -- why do you guys have to be special ;)

/test

**Pull request merged**
