### PR TITLE
Prevent picking the same route service twice

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1356003

@jwforres PTAL

### CODE REVIEW

**Comment by jwforres** [comment]
changes LGTM but we should make sure with the API folks that we want to prevent it, otherwise could get in a case where someone does it through API / CLI and then goes to edit it in the console and cant

**Comment by spadgett** [comment]
@rajatchopra Can you weight in? See

https://bugzilla.redhat.com/show_bug.cgi?id=1356003#c3

> Should the API allow you specify the same service twice in `route.spec.alternateBackends`? I'd expect that to fail validation.

**Comment by rajatchopra** [comment]
This looks good. But the API validation does not deal with it yet. It should. Let me fix up a PR for that soon.

Also, the API calls it alternateBackends, this piece of code calls it alternateServices. Fix one or the other?

**Comment by rajatchopra** [comment]
https://github.com/openshift/origin/pull/9920

**Comment by spadgett** [comment]
> Also, the API calls it alternateBackends, this piece of code calls it alternateServices. Fix one or the other?

Yeah, I purposely chose `alternateServices` to make it clear the web console code only supports services now. We show an error page if you edit a route with anything else.

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/edit/route.js#L73-L81

We use the correct property when calling the API.

https://github.com/openshift/origin-web-console/blob/master/app/scripts/controllers/edit/route.js#L113-L124

**Comment by spadgett** [comment]
@jwforres okay to merge?

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
