### PR TITLE
Send propagationPolicy null so that instances and bindings can be deleted cleanly

### PR DESCRIPTION
**Pull request by jwforres**
Depends on https://github.com/openshift/origin-web-common/pull/113

### CODE REVIEW

**Comment by jwforres** [comment]
Waiting on next release of common

**Comment by spadgett** [comment]
LGTM

**Comment by spadgett** [comment]
Should we worry about the other resources page? Now that we have the aggregator, service catalog resources are showing up

**Comment by jwforres** [comment]
Yeah good catch, we should either block them from showing up or handle the
delete correctly there. Main reason I would consider having them not
showing up is the editing experience, I don't know how much of update the
svc catalog is handling properly.

On Jun 19, 2017 9:56 PM, "Sam Padgett" <notifications@github.com> wrote:

Should we worry about the other resources page? Now that we have the
aggregator, service catalog resources are showing up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openshift/origin-web-console/pull/1739#issuecomment-309622367>,
or mute the thread

**Comment by spadgett** [comment]
[merge][severity:blocker]

**Pull request merged**
