### PR TITLE
[enterprise-3.9] Update key-validator regexp for key-value-editor

### PR DESCRIPTION
**Pull request by jhadvig**
Backport of https://github.com/openshift/origin-web-console/pull/3052

@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
I'm not sure why the jenkins tests fail on this branch. I restarted the travis build to at least check our dist.

cc @stevekuznetsov

**Comment by stevekuznetsov** [comment]
@spadgett can you use the issue tracker in the `openshift/release` repo to detail the issue here?

**Comment by spadgett** [comment]
Thanks, opened issue https://github.com/openshift/release/issues/1352

**Comment by jhadvig** [comment]
@spadgett can you ptal :)

**Comment by jhadvig** [comment]
Last test error:
```
1) User adds a template to a project after creating a new project using the Import YAML tab should save the template in the project catalog
  - Error: URL hasn't changed to project/console-test-project-1549296639180/create(is currently: undefined)
Wait timed out after 5036ms
  Wait timed out after 5036ms
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1425:29
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at then (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:522:7)
    at Object.webdriver.promise.asap (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:767:11)
    at newFrame.onComplete (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1670:25)
    at webdriver.promise.Frame_.notify_ (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1914:5)
    at Timeout._onTimeout (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1901:11)
    at ontimeout (timers.js:386:11)
==== async task ====
URL hasn't changed to project/console-test-project-1549296639180/create(is currently: undefined)
    at webdriver.promise.ControlFlow.wait (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1410:15)
    at webdriver.WebDriver.wait (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:646:21)
    at Protractor.to.(anonymous function) [as wait] (/data/src/github.com/openshift/origin-web-console/node_modules/protractor/lib/protractor.js:62:25)
    at waitForUri (/data/src/github.com/openshift/origin-web-console/test/integration/helpers.js:52:18)
    at browser.get.then (/data/src/github.com/openshift/origin-web-console/test/integration/helpers.js:104:12)
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/goog/base.js:1582:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1654:20)
    at notify (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:465:12)
    at notifyAll (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:442:7)
==== async task ====
Asynchronous test function: it()
    at .<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/jasminewd/index.js:93:33)
    at .<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/minijasminenode/lib/async-callback.js:45:37)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
Error
    at describe (/data/src/github.com/openshift/origin-web-console/test/integration/features/user_adds_template_to_project.spec.js:54:7)
    at describe (/data/src/github.com/openshift/origin-web-console/test/integration/features/user_adds_template_to_project.spec.js:25:5)
    at describe (/data/src/github.com/openshift/origin-web-console/test/integration/features/user_adds_template_to_project.spec.js:24:3)
```

**Pull request merged**
