### PR TITLE
Removing top margin causing unnecessary above the .log-header on the monitoring page.

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://github.com/openshift/origin-web-console/issues/1233

screen shot 2017-02-09 at 3 03 43 pm
screen shot 2017-02-09 at 3 04 13 pm

### CODE REVIEW

**Comment by spadgett** [comment]
Can you check a pod with multiple containers and chromeless logs?

> oc create -f https://raw.githubusercontent.com/openshift-qe/v3-testfiles/master/pods/pod_with_two_containers.json

**Comment by sg00dwin** [comment]
Updated PR so that `.log-header` containing a `ui-select` has adequate spacing between it and the logs.

screen shot 2017-02-10 at 4 36 16 pm

**Comment by sg00dwin** [comment]
@spadgett anything needed for this to move forward?

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
