### PR TITLE
[WIP] Show deployment in breadcrumbs for pod

### PR DESCRIPTION
**Pull request by spadgett**
When the pod is part of a deployment, show the deployment config and deployment number as links in the breadcrumbs.

See #319

screen_shot_2016-12-14_at_1_22_42_pm

### CODE REVIEW

**Comment by spadgett** [comment]
@jwforres Opinion on this change? I can't decide.

It's nice for navigation, but it's not obvious that you're looking at a pod. The type in the breadcrumbs was the only clue. I feel like that's a general problem we should solve, though.

**Comment by spadgett** [comment]
Might be better just to link to the deployment config and deployment somewhere in the page content

**Comment by jwforres** [comment]
If I had navigated to the page from the deployment page I could see it, but if I navigated there from the pods page it would be weird that my breadcrumb didn't reflect that.  I say keep it how we have it and your other PR at least gets us the easy link back.

**Comment by spadgett** [comment]
Fair enough, closing for now

**Pull request closed without merging**
