### PR TITLE
Removing flexbox mixin, removing invalid .pad-auto-*()

### PR DESCRIPTION
**Pull request by rhamilto**
Flexbox no longer requires prefixes for the browsers we support, so this PR removes the flexbox mixin that adds browser-specific prefixes to flexbox properties.

Additionally, this PR removes .pad-auto-* from the spacers mixin as auto is not a valid value for padding.

cc: @benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
+1 and we use autoprefixer

**Comment by sg00dwin** [comment]
Looks good

**Comment by spadgett** [comment]
@rhamilto I assume you prefer this to #1613?

**Comment by jwforres** [comment]
@rhamilto conflict on dist now, rebase / rebuild please

**Comment by rhamilto** [comment]
> @rhamilto I assume you prefer this to #1613?

Yep.  Just put both up so we could choose.

> @rhamilto conflict on dist now, rebase / rebuild please

Done.

**Comment by spadgett** [comment]
Thanks @rhamilto 

[merge]

**Pull request merged**
