### PR TITLE
Make nav-project-menu background transparent to fix …

### PR DESCRIPTION
**Pull request by sg00dwin**
fixes https://github.com/openshift/origin-web-console/issues/170

@spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
@sg00dwin Does the dropdown menu size correctly when open? It didn't for me when I tried that change.

**Comment by sg00dwin** [comment]
@spadgett it is resizing correctly for me. the change is just overriding the .form-control background color to transparent, so I don't see how that could be effecting the resize. 

possibly an existing bug non-related?

**Comment by spadgett** [comment]
This is what I mean. The menu when open is wider than it should be.

screen shot 2016-07-22 at 10 30 44 am

**Comment by sg00dwin** [comment]
@spadgett ok see it now, when the 'add to project' button is not shown. So it's related to Robs https://github.com/openshift/origin-web-console/pull/196

I'm looking at what needs to change and include that with this pull.

**Comment by sg00dwin** [comment]
@spadgett updated the pr with a fix for the resized project menu issue. PTAL
screen shot 2016-07-22 at 12 42 38 pm

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
