### PR TITLE
Bug 1504819: Obfuscate webhook trigger URL if user cant list secrets

### PR DESCRIPTION
**Pull request by jhadvig**
Removed the `copy-webhook-url` component and used `copy-to-clipboard` original since we decided to not show the warning tooltip and just obfuscate webhook URL is user doesnt have permissions to list secrets.
@jwforres PTAL

### CODE REVIEW

**Comment by jhadvig** [comment]
@jwforres added the warning tooltip next to the Trigger section header:
download

PTAL

**Comment by jhadvig** [comment]
@jwforres can we merge this ? Its the last bug on the [card](https://trello.com/c/lo6HwQgu/1106-2-build-webhooks-with-secretrefs)

**Comment by jwforres** [comment]
yeah i think this is fine for now, I think we probably want to consider if there are better alternatives that we could look at in 3.10 @ncameronbritt that have a different representation for users that don't have access to Secrets.  I can't decide if its helpful to have the webhook URLs there when they don't contain the actual secret.

**Comment by ncameronbritt** [comment]
That's certainly something we can look at. I'm not sure that using the warning icon is the right thing to do since there's not actually a problem with the platform. And if the user cannot use the webhook without the secret, I don't know that there is much value in showing the URL. Should we create an issue to follow up on this?

**Comment by jwforres** [comment]
Yep plz open an issue

**Pull request merged**
