### PR TITLE
Improve organization of catalog content

### PR DESCRIPTION
**Pull request by spadgett**
https://trello.com/c/xlQaSaxT
Fixes https://github.com/openshift/origin/issues/6175

catalog

/cc @rhamilto @sspeiche @luciddreamz

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by spadgett** [comment]
[merge]

**Comment by ajacobs21e** [comment]
@spadgett @rhamilto Is the breadcrumb switched? It should be Add to Project >> Catalog

**Comment by spadgett** [comment]
> Is the breadcrumb switched? It should be Add to Project >> Catalog

@ajacobs21e It's not, but I'll fix. Thanks for catching it.

**Comment by ajacobs21e** [comment]
Thanks Sam!

**Pull request merged**
