### PR TITLE
Redesigned web console overview

### PR DESCRIPTION
**Pull request by spadgett**
This is a collaborative effort by Jessica Forrester, Fabiano Franz, Steve Goodwin, and Sam Padgett based on designs by Allie Jacobs and SJ Cox.

Updates to the overview page include:

* New look and feel
* Service grouping
* Deployment metrics directly on the overview
* Notifications and alerts about deployment status on the overview
* Overview pipeline visualization

https://trello.com/c/N1k6Seml

@jwforres @fabianofranz @sg00dwin @ajacobs21e @ALRubinger

### CODE REVIEW

**Comment by spadgett** [comment]
[test]

**Comment by ALRubinger** [comment]
Keepin it :100:

**Comment by liggitt** [comment]
screenshot or it didn't happen :)

**Comment by fabianofranz** [comment]
@liggitt sure:

screenshot_014

**Comment by liggitt** [comment]
I can see why Sam wanted to spread the credit

**Comment by spadgett** [comment]
Best viewed in Netscape Navigator 4.0.

**Comment by smarterclayton** [comment]
Navigator 4.0 was awesome.  Also, that screenshot makes me want to dredge up the website I made when I was 16 using POVray to render the text in marble.  Must... find...

**Comment by jwforres** [comment]
Here goes...
[merge]

**Comment by fabianofranz** [comment]
> Navigator 4.0 was awesome

Yeah, specially on OS/2 Warp and when you are doing DHTML.<sup>1</sup>

<sup>1</sup>true story :)

**Comment by ajacobs21e** [comment]
bitmoji

**Pull request merged**
