### PR TITLE
Should use apis group for webhook URL as CLI

### PR DESCRIPTION
**Pull request by jhadvig**
@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
Hm...

```
+ oc cluster up --version=latest --public-hostname=localhost --loglevel=5 --server-loglevel=5
Error: invalid argument "latest" for --version=latest: strconv.ParseBool: parsing "latest": invalid syntax
```

@deads2k

**Comment by spadgett** [comment]
Looks like https://github.com/openshift/origin/pull/18938 broke our merge queue :(

**Comment by deads2k** [comment]
> Looks like openshift/origin#18938 broke our merge queue :(

Ah.  You'll want `--tag` then.  And remember its hidden now.

**Comment by spadgett** [comment]
Opened #2912

**Pull request merged**
