### PR TITLE
Bump openshift-jvm to 1.1.3

### PR DESCRIPTION
**Pull request by jwforres**

### CODE REVIEW

**Comment by jwforres** [comment]
[merge]

**Comment by jwforres** [comment]
[merge]

**Comment by spadgett** [comment]
> Built dist does not match what is committed, run 'grunt build' and include the results in your commit.

**Comment by jwforres** [comment]
@spadgett i'm running out of ideas.  I fixed the Gruntfile's clean task to make sure it was getting rid of existing dist.java/ files, I cleared out all of Travis's caches in case it was an npm dep in the build chain that is different. It is still failing on something with dist.java/java/style.css

**Comment by jwforres** [comment]
i'm adding verbose to the git status to see what the diff actually looks like...

**Comment by jwforres** [comment]
replaced by https://github.com/openshift/origin-web-console/pull/1214

**Pull request closed without merging**
