### PR TITLE
Point to Jenkinsfile when no pipeline builds have run

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin-web-console/issues/939

### CODE REVIEW

**Comment by jwforres** [comment]
jenkinsfile-embedded

jenkinsfile-path

jenkinsfile-bc-page

**Comment by jwforres** [comment]
@danmcp @spadgett PTAL

**Comment by danmcp** [comment]
I love it.

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
