### PR TITLE
Add support for AMQ 7 Broker in Java console (3.9)

### PR DESCRIPTION
**Pull request by abkieling**
A new release of hawtio/openshift-jvm has been made to include the hawtio-artemis plugin, which adds support for AMQ 7 Brokers.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by abkieling** [comment]
Can we try running the Jenkins job again?

**Comment by spadgett** [comment]
@alexkieling Jenkins jobs are broken on this branch.

**Pull request merged**
