### PR TITLE
Add filter for searching projects

### PR DESCRIPTION
**Pull request by tb120**
When there are a large amount of projects, finding a specific project can be inconvenient because the projects are in a list and that list can be extensive. I have added a simple keyword filter to allow users to more easily find the desired project(s).

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
See PR #199 for another take on project filtering.

**Comment by tb120** [comment]
@benjaminapetersen I didn't know about the Trello board and subsquently that someone was working on improving the projects page. Given that #199 has significantly more features and was tasked, should I close this request?

**Comment by jwforres** [comment]
thanks for the contribution, closing this since #199 is covering it, but we welcome feedback on that PR / feature

**Comment by benjaminapetersen** [comment]
Yup, thanks @tb120

**Pull request closed without merging**
