### PR TITLE
Use a context root with the dev server

### PR DESCRIPTION
**Pull request by jwforres**
Fixes https://github.com/openshift/origin/issues/3479

### CODE REVIEW

**Comment by jwforres** [comment]
@spadgett PTAL

[test]

**Comment by jwforres** [comment]
@juanvallejo @fabianofranz @jhadvig @MarkDeMaria can one of you guys try this out and validate everything works ok on fedora.

**Comment by juanvallejo** [comment]
Tested with Fedora 23 and Google Chrome, everything seems to be working ok

**Comment by fabianofranz** [comment]
Tried on F24 + Chrome with `oc cluster up` and `grunt serve` and it worked fine. I had to delete my `app/config.local.js` to get the changed `oauth_redirect_base`.

**Comment by jwforres** [comment]
@fabianofranz yep expected that folks will need to update config.local.js, when this goes in i'll send out a reminder to everyone :)

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
