### PR TITLE
Add EnvironmentService unit tests

### PR DESCRIPTION
**Pull request by spadgett**
Follow on to #1171

### CODE REVIEW

**Comment by jwforres** [comment]
LGTM, can merge if travis passes

**Comment by benjaminapetersen** [comment]
yay! tests :smile:

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
Unit tests passed, unrelated flake:

```
/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
      throw error;
      ^

Error: Timed out waiting for the WebDriver server at http://172.18.0.88:34074/wd/hub
    at Error (native)
    at onResponse (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:87:11)
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:42:21
    at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
    at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/index.js:145:7)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
>> /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/promise.js:1761
>>       throw error;
>>       ^
>> 
>> Error: Timed out waiting for the WebDriver server at http://172.18.0.88:34074/wd/hub
>>     at Error (native)
>>     at onResponse (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:87:11)
>>     at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/util.js:42:21
>>     at /data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/lib/webdriver/http/http.js:96:5
>>     at ClientRequest.<anonymous> (/data/src/github.com/openshift/origin-web-console/node_modules/selenium-webdriver/http/index.js:145:7)
>>     at emitOne (events.js:96:13)
>>     at ClientRequest.emit (events.js:188:7)
>>     at Socket.socketErrorListener (_http_client.js:310:9)
>>     at emitOne (events.js:96:13)
>>     at Socket.emit (events.js:188:7)
Fatal error: protractor exited with code: 1
```

[merge]

**Comment by spadgett** [comment]
@jwforres FYI, same merge error as before. I don't think it's related to the new tests.

[merge]

**Pull request merged**
