### PR TITLE
Increase default Jasmine timeout interval

### PR DESCRIPTION
**Pull request by spadgett**
Some tests do a lot of setup in `beforeEach`, including deleting and
recreating projects, which can cause tests to timeout with the
current value.

Also remove quotes from some test descriptions that break download links
for failure screenshots in Jenkins.

### CODE REVIEW

**Comment by jwforres** [comment]
@benjaminapetersen FYI, dont use " chars in test names, breaks screenshot reporting

[merge]

**Comment by jwforres** [comment]
as a follow-on we could probably make our screen-shot reporter file naming more robust, its in protractor.conf.js  Right now it just joins the "descriptions" with spaces

**Comment by spadgett** [comment]
@jwforres @benjaminapetersen Looking at a real fix for the special characters in #1524

**Comment by spadgett** [comment]
[merge]

**Comment by benjaminapetersen** [comment]
Ahh, oop, yeah prob we should update the file naming.  `_.kebabCase`, `_.snakeCaes` & `_.camelCase` will all eliminate those characters.  Hmm.

**Comment by spadgett** [comment]
@benjaminapetersen Not sure we can use Lodash in protractor.conf.js

**Comment by benjaminapetersen** [comment]
@spadgett should be able to, I'm using it in `protractor-mac.conf.js` to `extend()` the basic conf & eliminate the duplication.  I can take a look at updating this piece.

**Comment by spadgett** [comment]
[merge]

**Comment by spadgett** [comment]
[merge]

**Pull request merged**
