### PR TITLE
Use a monospace font when displaying config map values

### PR DESCRIPTION
**Pull request by spadgett**
@jwforres PTAL

openshift_web_console

### CODE REVIEW

**Comment by jwforres** [comment]
should we make the keys monospace too?

**Comment by spadgett** [comment]
For comparison:

openshift_web_console

**Comment by jwforres** [comment]
im leaning towards the consistent font style, whats your opinion?

@rhamilto opinion?

**Comment by spadgett** [comment]
> im leaning towards the consistent font style

Yeah I think I agree. Current commit changes both key and value to monospace.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
