### PR TITLE
Update masthead background color and border/inset colors.

### PR DESCRIPTION
**Pull request by sg00dwin**
New masthead hex color #1c2127
Slight adjustments to the border and inset colors so they maintain the current level of contrast between themselves and the background color.

**New header**
new-closed
new-open

**Old header**
old-closed
old-open

### CODE REVIEW

**Comment by sg00dwin** [comment]
@rhamilto @jwforres @spadgett

**Comment by rhamilto** [comment]
Nice job, @sg00dwin!  LGTM.  

We'll want to double check this against #1382, however.   I don't think there will be a problem based on a cursory look at both, but I may have missed something...

**Comment by jwforres** [comment]
I'm without question going to have to rebase #1382 so don't hold this out on that, if there is an issue we can tweak it there.

**Comment by jwforres** [comment]
[merge]

**Pull request merged**
